version: 2
models:
  - name: rpt_le_daily_advances_ticket
    description:  '{{ doc("rpt_le_daily_advances_ticket") }}'
    columns:
        - name: venue_city
          description: Indicates Venue city
        - name: cityname
          description: Cityname of the event 
        - name: venue_nm
          description: Venue name of upcoming event
        - name: brand_nm
          description: Indicates brand name
        - name: event_Type_cd
          description: Indicates event types 
        - name: event_date
          description: Date of the event
        - name: days_to_event
          description: Days to the event from current date
        - name: comp_type
          description: Indicates combination types like Actuals,Best comp,Average of comps
        - name: event_capacity 
          description: Indicates event capacity
        - name: gross
          description: Gross amount from LES
        - name: paid
          description: Paid number of tickets from LES
        - name: util
          description: Indicates utilization
        - name: fgross
          description: forcasted Gross amount from LES
        - name: fpaid
          description: Forcasted Paid number of tickets from LES
        - name: futil
          description: Forcasted utilization
        - name: maxeventdate
          description: event date
        - name: orders
          description: Indicate order
          
  - name: vw_rpt_le_daily_advances_ticket
    description:  '{{ doc("vw_rpt_le_daily_advances_ticket")}}'
    columns:
        - name: venue_city
          description: Indicates Venue city
        - name: cityname
          description: Cityname of the event 
        - name: venue_nm
          description: Venue name of upcoming event
        - name: brand_nm
          description: Indicates brand name
        - name: event_Type_cd
          description: Indicates event types 
        - name: event_date
          description: Date of the event
        - name: days_to_event
          description: Days to the event from current date
        - name: comp_type
          description: Indicates combination types like Actuals,Best comp,Average of comps
        - name: event_capacity 
          description: Indicates event capacity
        - name: gross
          description: Gross amount from LES
        - name: paid
          description: Paid number of tickets from LES
        - name: util
          description: Indicates utilization
        - name: fgross
          description: forcasted Gross amount from LES
        - name: fpaid
          description: Forcasted Paid number of tickets from LES
        - name: futil
          description: Forcasted utilization
        - name: maxeventdate
          description: event date
        - name: orders
          description: Indicate order
          
  - name: rpt_le_daily_stubhub_events_data
    description: '{{ doc("rpt_le_daily_stubhub_events_data") }}'
    columns:
        - name: id
          description: ID of the event
        - name: status
          description: Indicate the status of the event
        - name: locale
          description: Gives locale detail
        - name: name
          description: Name of the event
        - name: description
          description: Description of the event
        - name: weburi
          description: weburi of the event
        - name: eventdatelocal
          description: Event date in local timezone
        - name: eventdateutc
          description: Event date in UTC
        - name: createddate 
          description: Created date
        - name: lastupdateddate
          description: Last updated date
        - name: hideeventdate
          description: Indicates whether event date is hidden or not 
        - name: hideeventtime
          description: Indicates whether event time is hidden or not
        - name: venue_id
          description: Id of the event's venue
        - name: venue_name
          description: Name of the venue
        - name: venue_city
          description: Venue City
        - name: venue_state
          description: Venue State
        - name: venue_postalcode
          description:  Venue postal code
        - name: venue_country
          description: Venue Country
        - name: venue_venueconfigid
          description: Venue config id
        - name: venue_venueconfigname
          description: Venue config name
        - name: venue_latitude
          description: Latitude of the venue
        - name: venue_longitude
          description: Longitude of the venue
        - name: timezone
          description: Timezone detail
        - name: performers_0_id
          description: Performer's id
        - name: performers_0_name
          description: Performer's name
        - name: ancestors_categories_0_id
          description: Category ID
        - name: ancestors_categories_0_name
          description: Category name
        - name: ancestors_categories_1_id 
          description: Sub-Category ID
        - name: ancestors_categories_1_name
          description: Sub-Category Name
        - name: ancestors_groupings
          description: Ancestor Groupings
        - name: ancestors_performers_0_id
          description: Ancestors performer's id
        - name: ancestors_performers_0_name
          description: Ancestors performer's name
        - name: categoriescollection_categories_0_id
          description: Category collection ID
        - name: categoriescollection_categories_0_name
          description: Category Collection Name
        - name: currencycode
          description: Currency Code
        - name: ticketinfo_minprice
          description: Ticket Minimum Price
        - name: ticketinfo_minlistprice
          description: Ticket Minimum List Price
        - name: ticketinfo_maxlistprice
          description: Ticket Maximum List Price
        - name: ticketinfo_totaltickets
          description: Total Tickets Count
        - name: ticketinfo_totallistings
          description: Total Listings
        - name: ancestors_groupings_0_id
          description: Ancestor grouping's id
        - name: ancestors_groupings_0_name
          description: Ancestor grouping's name
        - name: categoriescollection_categories_1_id
          description: Category collection subset ID
        - name: categoriescollection_categories_1_name
          description: Category collection subset name
        - name: categoriescollection_categories_2_id
          description: Category collection sub ID
        - name: categoriescollection_categories_2_name
          description: Category collection sub name
        - name: performers_1_id
          description: Performer's sub id
        - name: performers_1_name
          description: Performer's sub name
        - name: performers_1_role 
          description: Performer's sub role
        - name: performers_0_role
          description: Performer's role 
        - name: ancestors_groupings_1_id
          description: Ancestor grouping's sub id
        - name: ancestors_groupings_1_name
          description: Ancestor grouping's sub name
        - name: report_date
          description: Reporting date
        - name: file_name
          description: File name
        - name: etl_batch_id_source
          description: ETL Batch ID at source
        - name: etl_insert_rec_dttm_source
          description: ETL insert record timestamp at source
        - name: etl_insert_user_id_source
          description: ETL insert user id at source
        - name: etl_update_rec_dttm_source
          description: ETL Update record timestamp at source
        - name: etl_update_user_id_source
          description: ETL Update user id at source
        - name: as_on_date
          description: As on date
        - name: event_year
          description: Event year
        - name: event_month
          description: Event Month
        - name: event_day
          description: Event Day
        - name: eventdatelocal_2 
          description: Event Local Date
        - name: as_on_date_2
          description: As on date in date format
        - name: as_on_date_rank
          description: As on date rank
        - name: event_dropped_flag
          description: Indicates whether event got dropped or not
        - name: event_added_flag
          description: Indicates whether event got added or not
        - name: last_updated_within_15_days_flag
          description: Indicates whether event record updated within 15 days or not
        - name: total_listings_changed_flag
          description: Indicates whether event's total listing changed or not
        - name: last_updated_date_changed_flag
          description: Indicates whether last updated date of event got changed or not
        - name: event_created_for_parking_flag
          description: Indicates whether event created for parking or not
        - name: etl_batch_id          
          description: Unique ID of DBT Job used to insert the record
        - name: etl_insert_user_id          
          description: Unique ID of the DBT user that was used to insert the record
        - name: etl_insert_rec_dttm          
          description: Date Time information on when the DBT inserted the record
        - name: etl_update_user_id          
          description: Unique ID of the DBT user which was used to update the record manually
        - name: etl_update_rec_dttm          
          description: Date Time information on when the record was updated

  - name: vw_rpt_le_daily_stubhub_events_data
    description:  '{{ doc("vw_rpt_le_daily_stubhub_events_data") }}'
    columns:
        - name: id
          description: ID of the event
        - name: status
          description: Indicate the status of the event
        - name: locale
          description: Gives locale detail
        - name: name
          description: Name of the event
        - name: description
          description: Description of the event
        - name: weburi
          description: weburi of the event
        - name: eventdatelocal
          description: Event date in local timezone
        - name: eventdateutc
          description: Event date in UTC
        - name: createddate 
          description: Created date
        - name: lastupdateddate
          description: Last updated date
        - name: hideeventdate
          description: Indicates whether event date is hidden or not 
        - name: hideeventtime
          description: Indicates whether event time is hidden or not
        - name: venue_id
          description: Id of the event's venue
        - name: venue_name
          description: Name of the venue
        - name: venue_city
          description: Venue City
        - name: venue_state
          description: Venue State
        - name: venue_postalcode
          description:  Venue postal code
        - name: venue_country
          description: Venue Country
        - name: venue_venueconfigid
          description: Venue config id
        - name: venue_venueconfigname
          description: Venue config name
        - name: venue_latitude
          description: Latitude of the venue
        - name: venue_longitude
          description: Longitude of the venue
        - name: timezone
          description: Timezone detail
        - name: performers_0_id
          description: Performer's id
        - name: performers_0_name
          description: Performer's name
        - name: ancestors_categories_0_id
          description: Category ID
        - name: ancestors_categories_0_name
          description: Category name
        - name: ancestors_categories_1_id 
          description: Sub-Category ID
        - name: ancestors_categories_1_name
          description: Sub-Category Name
        - name: ancestors_groupings
          description: Ancestor Groupings
        - name: ancestors_performers_0_id
          description: Ancestors performer's id
        - name: ancestors_performers_0_name
          description: Ancestors performer's name
        - name: categoriescollection_categories_0_id
          description: Category collection ID
        - name: categoriescollection_categories_0_name
          description: Category Collection Name
        - name: currencycode
          description: Currency Code
        - name: ticketinfo_minprice
          description: Ticket Minimum Price
        - name: ticketinfo_minlistprice
          description: Ticket Minimum List Price
        - name: ticketinfo_maxlistprice
          description: Ticket Maximum List Price
        - name: ticketinfo_totaltickets
          description: Total Tickets Count
        - name: ticketinfo_totallistings
          description: Total Listings
        - name: ancestors_groupings_0_id
          description: Ancestor grouping's id
        - name: ancestors_groupings_0_name
          description: Ancestor grouping's name
        - name: categoriescollection_categories_1_id
          description: Category collection subset ID
        - name: categoriescollection_categories_1_name
          description: Category collection subset name
        - name: categoriescollection_categories_2_id
          description: Category collection sub ID
        - name: categoriescollection_categories_2_name
          description: Category collection sub name
        - name: performers_1_id
          description: Performer's sub id
        - name: performers_1_name
          description: Performer's sub name
        - name: performers_1_role 
          description: Performer's sub role
        - name: performers_0_role
          description: Performer's role 
        - name: ancestors_groupings_1_id
          description: Ancestor grouping's sub id
        - name: ancestors_groupings_1_name
          description: Ancestor grouping's sub name
        - name: report_date
          description: Reporting date
        - name: file_name
          description: File name
        - name: etl_batch_id_source
          description: ETL Batch ID at source
        - name: etl_insert_rec_dttm_source
          description: ETL insert record timestamp at source
        - name: etl_insert_user_id_source
          description: ETL insert user id at source
        - name: etl_update_rec_dttm_source
          description: ETL Update record timestamp at source
        - name: etl_update_user_id_source
          description: ETL Update user id at source
        - name: as_on_date
          description: As on date
        - name: event_year
          description: Event year
        - name: event_month
          description: Event Month
        - name: event_day
          description: Event Day
        - name: eventdatelocal_2 
          description: Event Local Date
        - name: as_on_date_2
          description: As on date in date format
        - name: as_on_date_rank
          description: As on date rank
        - name: event_dropped_flag
          description: Indicates whether event got dropped or not
        - name: event_added_flag
          description: Indicates whether event got added or not
        - name: last_updated_within_15_days_flag
          description: Indicates whether event record updated within 15 days or not
        - name: total_listings_changed_flag
          description: Indicates whether event's total listing changed or not
        - name: last_updated_date_changed_flag
          description: Indicates whether last updated date of event got changed or not
        - name: event_created_for_parking_flag
          description: Indicates whether event created for parking or not
        - name: etl_batch_id          
          description: Unique ID of DBT Job used to insert the record
        - name: etl_insert_user_id          
          description: Unique ID of the DBT user that was used to insert the record
        - name: etl_insert_rec_dttm          
          description: Date Time information on when the DBT inserted the record
        - name: etl_update_user_id          
          description: Unique ID of the DBT user which was used to update the record manually
        - name: etl_update_rec_dttm          
          description: Date Time information on when the record was updated
  - name: rpt_le_weekly_consolidated_kpi
    description: '{{ doc("rpt_le_weekly_consolidated_kpi") }}'
    columns:
        - name: granularity
          description: represents the cadence i.e. Weekly or MTD or YTD
        - name: platform
          description: represents the platform name i.e. 'Live Events'
        - name: type
          description: represents the type i.e. 'Live Events'
        - name: metric
          description: represents the metric name
        - name: year
          description: indicates the calendar year
        - name: month
          description: indicates the calendar month
        - name: week
          description: indicates the calendar week
        - name: start_date
          description: calander date representing the start date of the week
        - name: end_date
          description: calander date representing the end date of the week
        - name: value
          description: indicates the metric value for current year
        - name: prev_year
          description: indicates the previous calendar year
        - name: prev_year_week
          description: indicates the week of previous calendar year
        - name: prev_year_start_date
          description: calander date representing the previous year start date of the week
        - name: prev_year_end_date
          description: calander date representing the previous year end date of the week
        - name: prev_year_value
          description: indicates the metric value for previous year
          