version: 2
models:
  - name: vw_rpt_daily_ig_published_frame
    description: '{{ doc("vw_rpt_daily_ig_published_frame") }}'
    columns:
        - name: dim_smprovider_account_id
          description: Unique Identifier of the social media provider account id
        - name: dim_social_account_id
          description: Unique Identifier of the social account id
        - name: dim_platform_id
          description: Unique Identifier of the social media platform id
        - name: dim_story_id
          description: Unique Identifier of the social media story id
        - name: dim_content_type_id
          description: Unique Identifier of the content type published on social media
        - name: dim_video_id
          description: Unique Identifier of the social media video id
        - name: dim_media_id
          description: Unique Identifier of the social media id
        - name: dim_date_id
          description: Unique Identifier of the social media data received date from the provider
        - name: frame_date
          description: Frame date
        - name: story_name
          description: Name of the story
        - name: caption
          description: Number of caption on a caption tweet - Description of the media post
        - name: content_published_frame_time_secs
          description: Content published frame time in seconds
        - name: as_on_date
          description: Record as-on date
        
  - name: vw_rpt_daily_ig_published_post
    description: '{{ doc("vw_rpt_daily_ig_published_post") }}'
    columns:
        - name: dim_smprovider_account_id
          description: Unique Identifier of the social media provider account id
        - name: dim_social_account_id
          description: Unique Identifier of the social account id
        - name: dim_platform_id
          description: Unique Identifier of the social media platform id
        - name: dim_video_id
          description: Unique Identifier of the video id
        - name: dim_media_id
          description: Unique Identifier of the social media id
        - name: dim_content_type_id
          description: Unique Identifier of the content type published on social media
        - name: dim_date_id
          description: Unique Identifier of the social media data received date from the provider
        - name: post_date
          description: Date video posted 
        - name: caption
          description: Post description
        - name: content_published_post_time
          description: content published post time 
        - name: as_on_date
          description: Record as-on date
          
  - name: vw_rpt_daily_ig_published_story
    description: '{{ doc("vw_rpt_daily_ig_published_story") }}'
    columns:
        - name: dim_smprovider_account_id
          description: Unique Identifier of the social media provider account id
        - name: dim_social_account_id
          description: Unique Identifier of the social account id
        - name: dim_platform_id
          description: Unique Identifier of the social media platform id
        - name: dim_story_id
          description: Unique Identifier of the social media story id
        - name: dim_date_id
          description: Unique Identifier of the social media data received date from the provider          
        - name: number_of_story_posts
          description: count of story posts
        - name: content_published_story_time_secs
          description: content published story time seconds
        - name: as_on_date
          description: Record as-on date
        
