/*
************************************************************************************ 
Date : 08/28/2020
Version : 1.0
ViewName : aggr_cpg_daily_kit_sales
Schema : fds_cpg
Contributor : Rahul Chandran,Sudhakar Andugula
Frequency : Daily ; 08:00 A.M EST
Description : Aggregated CPG Daily Kit Sales Table consist of Sales details of WWE Kit products on daily-basis
**************************************************************************************/
/* date      | by      |    Details   */


CREATE TABLE
    fds_cpg.aggr_cpg_daily_kit_sales
    (
        dim_business_unit_id BIGINT ENCODE AZ64,
        dim_order_method_id BIGINT ENCODE AZ64,
        date_key INTEGER ENCODE AZ64,
        src_order_type CHARACTER VARYING(1) ENCODE LZO,
        dim_kit_item_id BIGINT ENCODE AZ64,
        dim_item_id BIGINT ENCODE AZ64,
        src_unit_cost NUMERIC(38,4) ENCODE AZ64,
        src_current_retail_price NUMERIC(38,4) ENCODE AZ64,
        src_units_ordered BIGINT ENCODE AZ64,
        src_units_shipped BIGINT ENCODE AZ64,
        units_returned BIGINT ENCODE AZ64,
        net_units_sold BIGINT ENCODE AZ64,
        demand_cogs_$ NUMERIC(38,4) ENCODE AZ64,
        shipped_cogs_$ NUMERIC(38,4) ENCODE AZ64,
        returned_cogs_$ NUMERIC(38,4) ENCODE AZ64,
        net_cogs_$ NUMERIC(38,4) ENCODE AZ64,
        demand_retail_$ NUMERIC(38,4) ENCODE AZ64,
        shipped_retail_$ NUMERIC(38,4) ENCODE AZ64,
        net_retail_$ NUMERIC(38,4) ENCODE AZ64,
        demand_sales_$ NUMERIC(38,5) ENCODE AZ64,
        shipped_sales_$ NUMERIC(38,5) ENCODE AZ64,
        returns_$ NUMERIC(38,5) ENCODE AZ64,
        net_sales_$ NUMERIC(38,5) ENCODE AZ64,
        demand_selling_margin_$ NUMERIC(38,5) ENCODE AZ64,
        shipped_selling_margin_$ NUMERIC(38,5) ENCODE AZ64,
        net_selling_margin_$ NUMERIC(38,5) ENCODE AZ64,
        other_amount INTEGER ENCODE AZ64,
        kit_units_sold INTEGER ENCODE AZ64,
        unit_cost_local DOUBLE PRECISION,
        current_retail_price_local DOUBLE PRECISION,
        demand_cogs_local DOUBLE PRECISION,
        shipped_cogs_local DOUBLE PRECISION,
        returned_cogs_local DOUBLE PRECISION,
        net_cogs_local DOUBLE PRECISION,
        demand_retail_local DOUBLE PRECISION,
        shipped_retail_local DOUBLE PRECISION,
        net_retail_local DOUBLE PRECISION,
        demand_sales_local DOUBLE PRECISION,
        shipped_sales_local DOUBLE PRECISION,
        returns_local DOUBLE PRECISION,
        net_sales_local DOUBLE PRECISION,
        demand_selling_margin_local DOUBLE PRECISION,
        shipped_selling_margin_local DOUBLE PRECISION,
        net_selling_margin_local DOUBLE PRECISION,
        other_amount_local INTEGER ENCODE AZ64,
        src_currency_code_from CHARACTER VARYING(5) ENCODE LZO,
        dim_shop_site_id BIGINT ENCODE AZ64,
        etl_batch_id CHARACTER VARYING(100) ENCODE LZO,
        etl_insert_user_id CHARACTER VARYING(100) ENCODE LZO,
        etl_insert_rec_dttm TIMESTAMP WITHOUT TIME ZONE ENCODE AZ64,
        etl_update_user_id CHARACTER VARYING(50) ENCODE LZO,
        etl_update_rec_dttm TIMESTAMP WITHOUT TIME ZONE ENCODE AZ64
    );
COMMENT ON TABLE fds_cpg.aggr_cpg_daily_kit_sales
IS
    'Aggregated CPG Daily Kit Sales Table consist of Sales details of WWE Kit products on daily-basis'
    ;
COMMENT ON COLUMN fds_cpg.aggr_cpg_daily_kit_sales.dim_business_unit_id
IS
    'Generated unique Id for each business unit from dim_cpg_business_unit table';
COMMENT ON COLUMN fds_cpg.aggr_cpg_daily_kit_sales.dim_order_method_id
IS
    'Autogenerated id from dim_cpg_order_method table';
COMMENT ON COLUMN fds_cpg.aggr_cpg_daily_kit_sales.date_key
IS
    'order date key';
COMMENT ON COLUMN fds_cpg.aggr_cpg_daily_kit_sales.src_order_type
IS
    'type of order';
COMMENT ON COLUMN fds_cpg.aggr_cpg_daily_kit_sales.dim_kit_item_id
IS
    'dim_kit_item_id referencing from dim_cpg_kit_item table';
COMMENT ON COLUMN fds_cpg.aggr_cpg_daily_kit_sales.dim_item_id
IS
    'References dim_item_id of dim_cpg_item table';
COMMENT ON COLUMN fds_cpg.aggr_cpg_daily_kit_sales.src_unit_cost
IS
    'Cost per Unit';
COMMENT ON COLUMN fds_cpg.aggr_cpg_daily_kit_sales.src_current_retail_price
IS
    'Current retail price';
COMMENT ON COLUMN fds_cpg.aggr_cpg_daily_kit_sales.src_units_ordered
IS
    'Number of Units Ordered';
COMMENT ON COLUMN fds_cpg.aggr_cpg_daily_kit_sales.src_units_shipped
IS
    'Number of units shipped';
COMMENT ON COLUMN fds_cpg.aggr_cpg_daily_kit_sales.units_returned
IS
    'Number of units returned';
COMMENT ON COLUMN fds_cpg.aggr_cpg_daily_kit_sales.net_units_sold
IS
    'Net units sold';
COMMENT ON COLUMN fds_cpg.aggr_cpg_daily_kit_sales.demand_cogs_$
IS
    'Demand COG Amount';
COMMENT ON COLUMN fds_cpg.aggr_cpg_daily_kit_sales.shipped_cogs_$
IS
    'Shipped COG Amount';
COMMENT ON COLUMN fds_cpg.aggr_cpg_daily_kit_sales.returned_cogs_$
IS
    'Returned COG Amount';
COMMENT ON COLUMN fds_cpg.aggr_cpg_daily_kit_sales.net_cogs_$
IS
    'Net COG Amount';
COMMENT ON COLUMN fds_cpg.aggr_cpg_daily_kit_sales.demand_retail_$
IS
    'Demand Retail Amount';
COMMENT ON COLUMN fds_cpg.aggr_cpg_daily_kit_sales.shipped_retail_$
IS
    'Shipped Retail Amount';
COMMENT ON COLUMN fds_cpg.aggr_cpg_daily_kit_sales.net_retail_$
IS
    'Net Retail Amount';
COMMENT ON COLUMN fds_cpg.aggr_cpg_daily_kit_sales.demand_sales_$
IS
    'Demand Sales Amount';
COMMENT ON COLUMN fds_cpg.aggr_cpg_daily_kit_sales.shipped_sales_$
IS
    'Shipped Sales Amount';
COMMENT ON COLUMN fds_cpg.aggr_cpg_daily_kit_sales.returns_$
IS
    'Return Sales Amount';
COMMENT ON COLUMN fds_cpg.aggr_cpg_daily_kit_sales.net_sales_$
IS
    'Net Sales Amount';
COMMENT ON COLUMN fds_cpg.aggr_cpg_daily_kit_sales.demand_selling_margin_$
IS
    'Demand Selling Margin Amount';
COMMENT ON COLUMN fds_cpg.aggr_cpg_daily_kit_sales.shipped_selling_margin_$
IS
    'Shipped Selling Margin Amount';
COMMENT ON COLUMN fds_cpg.aggr_cpg_daily_kit_sales.net_selling_margin_$
IS
    'Net Selling Margin Amount';
COMMENT ON COLUMN fds_cpg.aggr_cpg_daily_kit_sales.other_amount
IS
    'Other Amount';
COMMENT ON COLUMN fds_cpg.aggr_cpg_daily_kit_sales.kit_units_sold
IS
    'Number of Kit Units Sold';
COMMENT ON COLUMN fds_cpg.aggr_cpg_daily_kit_sales.unit_cost_local
IS
    'Cost per Unit in USD';
COMMENT ON COLUMN fds_cpg.aggr_cpg_daily_kit_sales.current_retail_price_local
IS
    'Current Retail Price in USD';
COMMENT ON COLUMN fds_cpg.aggr_cpg_daily_kit_sales.demand_cogs_local
IS
    'Demand COG Amount in USD';
COMMENT ON COLUMN fds_cpg.aggr_cpg_daily_kit_sales.shipped_cogs_local
IS
    'Shipped COG Amount in USD';
COMMENT ON COLUMN fds_cpg.aggr_cpg_daily_kit_sales.returned_cogs_local
IS
    'Returned COG Amount in USD';
COMMENT ON COLUMN fds_cpg.aggr_cpg_daily_kit_sales.net_cogs_local
IS
    'Net COG Amount in USD';
COMMENT ON COLUMN fds_cpg.aggr_cpg_daily_kit_sales.demand_retail_local
IS
    'Demand Retail Amount in USD';
COMMENT ON COLUMN fds_cpg.aggr_cpg_daily_kit_sales.shipped_retail_local
IS
    'Shipped Retail Amount in USD';
COMMENT ON COLUMN fds_cpg.aggr_cpg_daily_kit_sales.net_retail_local
IS
    'Net Retail Amount in USD';
COMMENT ON COLUMN fds_cpg.aggr_cpg_daily_kit_sales.demand_sales_local
IS
    'Demand Sales Amount in USD';
COMMENT ON COLUMN fds_cpg.aggr_cpg_daily_kit_sales.shipped_sales_local
IS
    'Shipped Sales Amount in USD';
COMMENT ON COLUMN fds_cpg.aggr_cpg_daily_kit_sales.returns_local
IS
    'Return Sales Amount in USD';
COMMENT ON COLUMN fds_cpg.aggr_cpg_daily_kit_sales.net_sales_local
IS
    'Net Sales Amount in USD';
COMMENT ON COLUMN fds_cpg.aggr_cpg_daily_kit_sales.demand_selling_margin_local
IS
    'Demand Selling Margin Amount in USD';
COMMENT ON COLUMN fds_cpg.aggr_cpg_daily_kit_sales.shipped_selling_margin_local
IS
    'Shipped Selling Margin Amount in USD';
COMMENT ON COLUMN fds_cpg.aggr_cpg_daily_kit_sales.net_selling_margin_local
IS
    'Net Selling Margin Amount in USD';
COMMENT ON COLUMN fds_cpg.aggr_cpg_daily_kit_sales.other_amount_local
IS
    'Other Amount in USD';
COMMENT ON COLUMN fds_cpg.aggr_cpg_daily_kit_sales.src_currency_code_from
IS
    'Currency code from';
COMMENT ON COLUMN fds_cpg.aggr_cpg_daily_kit_sales.dim_shop_site_id
IS
    'References dim_shop_site_id of dim_cpg_shop_site table';
COMMENT ON COLUMN fds_cpg.aggr_cpg_daily_kit_sales.etl_batch_id
IS
    'Unique ID of DBT Job used to insert the record';
COMMENT ON COLUMN fds_cpg.aggr_cpg_daily_kit_sales.etl_insert_user_id
IS
    'Unique ID of the DBT user that was used to insert the record';
COMMENT ON COLUMN fds_cpg.aggr_cpg_daily_kit_sales.etl_insert_rec_dttm
IS
    'Date Time information on when the DBT inserted the record';
COMMENT ON COLUMN fds_cpg.aggr_cpg_daily_kit_sales.etl_update_user_id
IS
    'Unique ID of the DBT user which was used to update the record manually';
COMMENT ON COLUMN fds_cpg.aggr_cpg_daily_kit_sales.etl_update_rec_dttm
IS
    'Date Time information on when the record was updated';