/*
*************************************************************************************************************************************************
   TableName   : rpt_nl_weekly_domestic_tagging
   Schema	   : fds_nl
   Contributor : B.V.Sai Praveen Chakravarthy
   Description : summary table for capturing the tagged attributes of properties 
                 by performing union of all the intermediate ephemeral tables
   Version      Date             Author               Request
   1.0          03/15/2021       pchakrav             ADVA-297
*************************************************************************************************************************************************
*/


{{ config(materialized='incremental',incremental_strategy='delete+insert',
enabled = true,tags=['domestic','tagging','summary'],
unique_key= "src_broadcast_orig_date||'-'||src_broadcast_network_id||'-'||program_telecast_rpt_starttime
||'-'||src_broadcast_network_service_type",
schema ='fds_nl',post_hook = "grant select on {{ this }} to DA_RBAVISETTY_USER_ROLE") }}

with rpt_nl_weekly_domestic_tagging AS 
    (SELECT src_broadcast_orig_date,
        broadcast_date,
        broadcast_network_name,
        src_series_name,
        src_episode_title,
        program_telecast_rpt_starttime,
        program_telecast_rpt_endtime,
         src_total_duration,
        src_playback_period_cd,
        src_demographic_group,
        src_genre_classification_cd,
        src_genre_classification_detailedtypecd,
         src_program_attributes,
        src_daypart_cd,
        src_broadcast_network_service_type,
        avg_audience_proj_000,
        avg_audience_proj_units,
        avg_audience_pct ,
         avg_audience_pct_nw_cvg_area,
        share_pct,
        share_pct_nw_cvg_area,
        telecast_trackage_name,
         calendardayofweekname,
        att_Shoulder,
        att_cup,
        att_season,
        att_Channel_Qualifier,
        src_broadcast_network_id,
        inserted_time,
        property
    FROM {{ref('intm_weekly_domestic_tagging_aew')}}
    UNION all
	SELECT src_broadcast_orig_date,
        broadcast_date,
        broadcast_network_name,
        src_series_name,
        src_episode_title,
        program_telecast_rpt_starttime,
        program_telecast_rpt_endtime,
         src_total_duration,
        src_playback_period_cd,
        src_demographic_group,
        src_genre_classification_cd,
        src_genre_classification_detailedtypecd,
         src_program_attributes,
        src_daypart_cd,
        src_broadcast_network_service_type,
        avg_audience_proj_000,
        avg_audience_proj_units,
        avg_audience_pct ,
         avg_audience_pct_nw_cvg_area,
        share_pct,
        share_pct_nw_cvg_area,
        telecast_trackage_name,
        calendardayofweekname,
        att_Shoulder,
        att_cup,
        att_season,
        att_Channel_Qualifier,
        src_broadcast_network_id,
        inserted_time,
        property
    FROM {{ref('intm_weekly_domestic_tagging_mlb')}}
    UNION all
	SELECT src_broadcast_orig_date,
        broadcast_date,
        broadcast_network_name,
        src_series_name,
        src_episode_title,
        program_telecast_rpt_starttime,
        program_telecast_rpt_endtime,
         src_total_duration,
        src_playback_period_cd,
        src_demographic_group,
        src_genre_classification_cd,
        src_genre_classification_detailedtypecd,
         src_program_attributes,
        src_daypart_cd,
        src_broadcast_network_service_type,
        avg_audience_proj_000,
        avg_audience_proj_units,
        avg_audience_pct ,
         avg_audience_pct_nw_cvg_area,
        share_pct,
        share_pct_nw_cvg_area,
        telecast_trackage_name,
        calendardayofweekname,
        att_Shoulder,
        att_cup,
        att_season,
        att_Channel_Qualifier,
        src_broadcast_network_id,
        inserted_time,
        property
    FROM {{ref('intm_weekly_domestic_tagging_nascar')}}
    UNION all
	SELECT src_broadcast_orig_date,
        broadcast_date,
        broadcast_network_name,
        src_series_name,
        src_episode_title,
        program_telecast_rpt_starttime,
        program_telecast_rpt_endtime,
         src_total_duration,
        src_playback_period_cd,
        src_demographic_group,
        src_genre_classification_cd,
        src_genre_classification_detailedtypecd,
         src_program_attributes,
        src_daypart_cd,
        src_broadcast_network_service_type,
        avg_audience_proj_000,
        avg_audience_proj_units,
        avg_audience_pct ,
         avg_audience_pct_nw_cvg_area,
        share_pct,
        share_pct_nw_cvg_area,
        telecast_trackage_name,
        calendardayofweekname,
        att_Shoulder,
        att_cup,
        att_season,
        att_Channel_Qualifier,
        src_broadcast_network_id,
        inserted_time,
        property
    FROM {{ref('intm_weekly_domestic_tagging_nba')}}
    UNION all
	SELECT src_broadcast_orig_date,
        broadcast_date,
        broadcast_network_name,
        src_series_name,
        src_episode_title,
        program_telecast_rpt_starttime,
        program_telecast_rpt_endtime,
         src_total_duration,
        src_playback_period_cd,
        src_demographic_group,
        src_genre_classification_cd,
        src_genre_classification_detailedtypecd,
         src_program_attributes,
        src_daypart_cd,
        src_broadcast_network_service_type,
        avg_audience_proj_000,
        avg_audience_proj_units,
        avg_audience_pct ,
         avg_audience_pct_nw_cvg_area,
        share_pct,
        share_pct_nw_cvg_area,
        telecast_trackage_name,
        calendardayofweekname,
        att_Shoulder,
        att_cup,
        att_season,
        att_Channel_Qualifier,
        src_broadcast_network_id,
        inserted_time,
        property
    FROM {{ref('intm_weekly_domestic_tagging_nfl')}}
    UNION all
	SELECT src_broadcast_orig_date,
        broadcast_date,
        broadcast_network_name,
        src_series_name,
        src_episode_title,
        program_telecast_rpt_starttime,
        program_telecast_rpt_endtime,
         src_total_duration,
        src_playback_period_cd,
        src_demographic_group,
        src_genre_classification_cd,
        src_genre_classification_detailedtypecd,
         src_program_attributes,
        src_daypart_cd,
        src_broadcast_network_service_type,
        avg_audience_proj_000,
        avg_audience_proj_units,
        avg_audience_pct ,
         avg_audience_pct_nw_cvg_area,
        share_pct,
        share_pct_nw_cvg_area,
        telecast_trackage_name,
        calendardayofweekname,
        att_Shoulder,
        att_cup,
        att_season,
        att_Channel_Qualifier,
        src_broadcast_network_id,
        inserted_time,
        property
    FROM {{ref('intm_weekly_domestic_tagging_nhl')}} )
SELECT src_broadcast_orig_date,
        broadcast_date,
        broadcast_network_name,
        src_series_name,
        src_episode_title,
        program_telecast_rpt_starttime,
        program_telecast_rpt_endtime,
         src_total_duration,
        src_playback_period_cd,
        src_demographic_group,
        src_genre_classification_cd,
        src_genre_classification_detailedtypecd,
         src_program_attributes,
        src_daypart_cd,
        src_broadcast_network_service_type,
        avg_audience_proj_000,
        avg_audience_proj_units,
        avg_audience_pct ,
         avg_audience_pct_nw_cvg_area,
        share_pct,
        share_pct_nw_cvg_area,
        telecast_trackage_name,
        calendardayofweekname,
        att_Shoulder,
        att_cup,
        att_season,
        att_Channel_Qualifier,
        src_broadcast_network_id,
        inserted_time,
        property,
        id,
        ROWNUMBER,
         'DBT_'||TO_CHAR(SYSDATE(),'YYYY_MM_DD_HH_MI_SS')||'_Inter' AS etl_batch_id , 'bi_dbt_user_prd' AS etl_insert_user_id , SYSDATE() AS etl_insert_rec_dttm , NULL AS etl_update_user_id , cast(null AS timestamp) AS etl_update_rec_dttm
FROM 
    (SELECT src_broadcast_orig_date,
        broadcast_date,
        broadcast_network_name,
        src_series_name,
        src_episode_title,
        program_telecast_rpt_starttime,
        program_telecast_rpt_endtime,
         src_total_duration,
        src_playback_period_cd,
        src_demographic_group,
        src_genre_classification_cd,
        src_genre_classification_detailedtypecd,
         src_program_attributes,
        src_daypart_cd,
        src_broadcast_network_service_type,
        avg_audience_proj_000,
        avg_audience_proj_units,
        avg_audience_pct ,
         avg_audience_pct_nw_cvg_area,
        share_pct,
        share_pct_nw_cvg_area,
        telecast_trackage_name,
        calendardayofweekname,
        att_Shoulder,
        att_cup,
        att_season,
        att_Channel_Qualifier,
        src_broadcast_network_id,
        inserted_time,
        property,
         src_broadcast_orig_date||'-'||src_broadcast_network_id||'-'||program_telecast_rpt_starttime ||'-'||src_broadcast_network_service_type AS id, ROW_NUMBER()
        OVER (partition by src_broadcast_orig_date, src_broadcast_network_id, program_telecast_rpt_starttime,src_broadcast_network_service_type
    ORDER BY  inserted_time desc) ROWNUMBER
    FROM rpt_nl_weekly_domestic_tagging )
WHERE ROWNUMBER =1 {% if is_incremental() %}
HAVING inserted_time > 
    (SELECT max(inserted_time)
    FROM {{ this }}) {% endif %} 