image: ubuntu

stages:
  - Dev
  
#Pre Deployment steps stage
Dev:   
   stage: Dev   
   before_script: 
     - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client git -y )'
     - eval $(ssh-agent -s)
     - mkdir ~/.ssh
     - echo "$SSH_PRIVATE_KEY" >> ~/.ssh/authorized_keys
     - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
     - chmod 700 ~/.ssh/*

   script: 
      - ssh -v -i ~/.ssh/authorized_keys "$PRD_USER"@"$PRD_IP" "cd ~/workspace/ && source virtualenv/bin/activate && cd analytics_engineering && touch test "
