name: analytics_engineering_marts
version: 1.0
profile: analytics_engineering_marts_profile

config-version: 2

vars:
  ###################################################################
  ########### VARIABLES FOR VIEWERSHIP CLUSTERING MODEL   ###########
  ###################################################################
  # viewership data end date, model run date, should be end of month
  as_on_date:
    # The `start_date` and `end_date` variable will be accessible in all resources
  start_date: '2021-01-19'
  end_date: '2021-01-31'


source-paths: ["models"]      # paths with source code to compile
target-path: "target"         # path for compiled code
test-paths: ["tests"]           # where to store test results
#macro-paths: ["macros"]

models:
    analytics_engineering_marts:
      Redshift:
         +post-hook: 'grant select on {{ this }} to public'
         +persist_docs: {'relation' : true, 'columns' : true}