name: analytics_engineering_marts 
version: 1.0

config-version: 2


profile: wwe_profile


source-paths: ["models"]      # paths with source code to compile
target-path: "target"         # path for compiled code
test-paths: ["tests"]           # where to store test results
#macro-paths: ["macros"]

vars:
  # The `start_date` and `end_date` variable will be accessible in all resources
  start_date: '2020-01-01'
  end_date: '2020-01-31'

models:
    analytics_engineering_marts :

