name: analytics_engineering_marts 
version: 1.0

config-version: 2


profile: wwe_profile


source-paths: ["models"]      # paths with source code to compile
target-path: "target"         # path for compiled code
test-paths: ["tests"]           # where to store test results
#macro-paths: ["macros"]

models:
    analytics_engineering_marts :

