version: 2
models:
  - name: vw_rpt_daily_sc_published_frame
    description: '{{ doc("vw_rpt_daily_sc_published_frame") }}'
    columns:
        - name: dim_smprovider_account_id
          description: Unique Identifier of the social media provider account id
        - name: dim_social_account_id
          description: Unique Identifier of the social account id
        - name: dim_platform_id
          description: Unique Identifier of the social media platform id
        - name: dim_story_id
          description: Unique Identifier of the social media story id
        - name: dim_content_type_id
          description: Unique Identifier of the content type published on social media
        - name: dim_video_id
          description: Unique Identifier of the social media video id
        - name: dim_media_id
          description: Unique Identifier of the social media id
        - name: dim_date_id
          description: Unique Identifier of the social media data received date from the provider
        - name: frame
          description: number of frame 
        - name: snap_time_posted
          description: Date snap time posted
        - name: as_on_date
          description: Record as-on date
        
  - name: vw_rpt_daily_sc_published_story
    description: '{{ doc("vw_rpt_daily_sc_published_story") }}'
    columns:
        - name: dim_smprovider_account_id
          description: Unique Identifier of the social media provider account id
        - name: dim_platform_id
          description: Unique Identifier of the social media platform id
        - name: dim_story_id
          description: Unique Identifier of the social media story id
        - name: dim_date_id
          description: Unique Identifier of the social media data received date from the provider 
        - name: story_start
          description: story start time
        - name: updated
          description: story end time
        - name: story_view_time_secs
          description: Story view time
        - name: as_on_date
          description: Record as-on date