{{
  config({
		'schema': 'fds_le',
		"materialized": 'table','tags': "Phase 5A","persist_docs": {'relation' : true, 'columns' : true},
		"post-hook": ['grant select on {{this}} to public', 'drop table fds_le.stg_le_daily_stubhub_events_data']
  })
}}
SELECT
    id,
    status,
    locale,
    name,
    description,
    weburi,
    eventdatelocal,
    eventdateutc,
    createddate,
    lastupdateddate,
    hideeventdate,
    hideeventtime,
    venue_id,
    venue_name,
    venue_city,
    venue_state,
    venue_postalcode,
    venue_country,
    venue_venueconfigid,
    venue_venueconfigname,
    venue_latitude,
    venue_longitude,
    timezone,
    performers_0_id,
    performers_0_name,
    ancestors_categories_0_id,
    ancestors_categories_0_name,
    ancestors_categories_1_id,
    ancestors_categories_1_name,
    ancestors_groupings,
    ancestors_performers_0_id,
    ancestors_performers_0_name,
    categoriescollection_categories_0_id,
    categoriescollection_categories_0_name,
    currencycode,
    ticketinfo_minprice,
    ticketinfo_minlistprice,
    ticketinfo_maxlistprice,
    ticketinfo_totaltickets,
    ticketinfo_totallistings,
    ancestors_groupings_0_id,
    ancestors_groupings_0_name,
    categoriescollection_categories_1_id,
    categoriescollection_categories_1_name,
    categoriescollection_categories_2_id,
    categoriescollection_categories_2_name,
    performers_1_id,
    performers_1_name,
    performers_1_role,
    performers_0_role,
    ancestors_groupings_1_id,
    ancestors_groupings_1_name,
    report_date,
    file_name,
    etl_batch_id as etl_batch_id_source,
    etl_insert_rec_dttm as etl_insert_rec_dttm_source,
    etl_insert_user_id as etl_insert_user_id_source,
    etl_update_rec_dttm as etl_update_rec_dttm_source,
    etl_update_user_id as etl_update_user_id_source,
    as_on_date,
    event_year,
    event_month,
    event_day,
    eventdatelocal_2,
    as_on_date_2,
    as_on_date_rank,
    event_dropped_flag,
    event_added_flag,
    last_updated_within_15_days_flag,
    total_listings_changed_flag,
    last_updated_date_changed_flag,
    event_created_for_parking_flag,
	('DBT_' || to_char(sysdate, 'YYYY_MM_DD_HH_MI_SS') || '_5A') as etl_batch_id,
    'bi_dbt_user_prd'                                            as etl_insert_user_id,
    sysdate                                                      as etl_insert_rec_dttm,
    cast(null as varchar(15))                                    as etl_update_user_id,
    cast(null as timestamp)                                      as etl_update_rec_dttm
	from 
	{{ref('intm_le_daily_stubhub_events_data')}}