CREATE TABLE RPT_NL_DAILY_WWE_PROGRAM_RATINGS (
	BROADCAST_DATE_ID NUMBER(38,0) COMMENT 'Broadcast Date ID Field',
	BROADCAST_DATE DATE COMMENT 'Derived dates based on the viewing period; before 6 am morning hours is the previous date broadcast hour',
	BROADCAST_CAL_WEEK_BEGIN_DATE DATE COMMENT 'Calendar Year Week Begin Date based on Broadcast Date',
	BROADCAST_CAL_WEEK_END_DATE DATE COMMENT 'Calendar Year Week End Date based on Broadcast Date',
	BROADCAST_CAL_WEEK_NUM NUMBER(38,0) COMMENT 'Calendar Year Week Number based on Broadcast Date',
	BROADCAST_CAL_MONTH_NUM NUMBER(38,0) COMMENT 'Calendar Year Month Number based on Broadcast Date',
	BROADCAST_CAL_MONTH_NM VARCHAR(20) COMMENT 'Calendar Year Month based on Broadcast Date',
	BROADCAST_CAL_QUARTER VARCHAR(20) COMMENT 'Calendar Year Quarter based on Broadcast Date',
	BROADCAST_CAL_YEAR NUMBER(38,0) COMMENT 'Calendar Year based on Broadcast Date',
	BROADCAST_FIN_WEEK_BEGIN_DATE DATE COMMENT 'Financial Year Week Begin Date based on Broadcast Date',
	BROADCAST_FIN_WEEK_END_DATE DATE COMMENT 'Financial Year Week End Date based on Broadcast Date',
	BROADCAST_FIN_WEEK_NUM NUMBER(38,0) COMMENT 'Financial Year Week Number based on Broadcast Date',
	BROADCAST_FIN_MONTH_NUM NUMBER(38,0) COMMENT 'Financial Year Month Number based on Broadcast Date',
	BROADCAST_FIN_MONTH_NM VARCHAR(20) COMMENT 'Financial Year Month based on Broadcast Date',
	BROADCAST_FIN_YEAR NUMBER(38,0) COMMENT 'Financial Year based on Broadcast Date',
	SRC_BROADCAST_NETWORK_ID NUMBER(38,0) COMMENT 'A unique numerical identifier for an individual programming originator.',
	BROADCAST_NETWORK_NAME VARCHAR(255) COMMENT 'Broadcast netowrk Name or the channel name or view source name',
	SRC_PLAYBACK_PERIOD_CD VARCHAR(255) COMMENT 'A comma separated list of data streams.',
	SRC_DEMOGRAPHIC_GROUP VARCHAR(255) COMMENT 'A comma separated list of demographic groups (e.g. Females 18 to 49 and Males 18 - 24 input as F18-49,M18-24).',
	SRC_PROGRAM_ID NUMBER(38,0) COMMENT 'A unique numerical identifier for an individual program nam.',
	SRC_SERIES_NAME VARCHAR(255) COMMENT 'A unique numerical identifier for an individual program name.',
	SRC_DAYPART_CD VARCHAR(255) COMMENT 'A unique character identifier for an individual daypart',
	SRC_DAYPART_NAME VARCHAR(255) COMMENT 'A unique character identifier for an individual daypart description',
	PROGRAM_TELECAST_RPT_STARTTIME VARCHAR(255) COMMENT 'The start time of the program telecast (HH:MM).',
	PROGRAM_TELECAST_RPT_ENDTIME VARCHAR(255) COMMENT 'The end time of the program telecast (HH:MM).',
	SRC_TOTAL_DURATION NUMBER(38,0) COMMENT 'The duration of the program/telecast airing (minutes).',
	AVG_AUDIENCE_PROJ_000 NUMBER(38,0) COMMENT 'Total U.S. Average Audience Projection (000) (The projected number of households tuned or persons viewing a program/originator/daypart during the average minute, expressed in thousands.)',
	AVG_AUDIENCE_PCT NUMBER(20,2) COMMENT 'Total U.S. Average Audience Percentage (The percentage of the target demographic viewing the average minute of the selected program or time period within the total U.S.)',
	AVG_AUDIENCE_PCT_NW_CVG_AREA NUMBER(20,2) COMMENT 'Coverage Area Average Audience Percent (The percentage of the target demographic viewing the average minute of a selected program or time period within a network’s coverage area.)',
	VIEWING_MINUTES_UNITS NUMBER(38,0) COMMENT 'Derived Average Viewing Hours in minutes',
	ETL_BATCH_ID VARCHAR(100) COMMENT 'Unique ID of DBT Job used to insert the record',
	ETL_INSERT_USER_ID VARCHAR(100) COMMENT 'Unique ID of the DBT user that was used to insert the record',
	ETL_INSERT_REC_DTTM TIMESTAMP_NTZ(9) COMMENT 'Date Time information on when the DBT inserted the record',
	ETL_UPDATE_USER_ID VARCHAR(50) COMMENT 'Unique ID of the DBT user which was used to update the record manually',
	ETL_UPDATE_REC_DTTM TIMESTAMP_NTZ(9) COMMENT 'Date Time information on when the record was updated',
	BROADCAST_FIN_QUARTER VARCHAR(16383)
)COMMENT='## Implementation Detail\n*   Date        : 07/21/2020\n*   Version     : 1.0\n*   TableName   : rpt_nl_daily_wwe_program_ratings\n*   Schema	    : fds_nl\n*   Contributor : Rahul Chandran\n*   Description : WWE Program Ratings Daily Report View consist of rating details of all WWE Programs referencing from Program Viewership Daily fact table on daily-basis\n\n## Schedule Details\n* Frequency : Daily ; 02:00 A.M EST (Wed-Mon) & 04:00 A.M EST (Tue)\n* Dependent Jobs (process_name ; process_id) : t_di_nielsen_fact_nl_program_viewership_ratings_daily_slot2_abac ; 12144 (Wed-Mon) & t_di_nielsen_fact_nl_program_viewership_ratings_abac ; 12121 (Tue)\n\n## Maintenance Log\n* Date : 07/21/2020 ; Developer: Rahul Chandran ; Change: Initial Version as a part of Phase 4b Project.\n* Date : 08/06/2020 ; Developer: Remya K Nair ; Change:TAB-2105,TAB-2106 :- Added src_series_name and excluded all the repeats while calculating the live viewership by including src_program_attributes filter.'
;