CREATE TABLE RPT_NL_DAILY_MINXMIN_LITE_LOG_RATINGS (
	BROADCAST_DATE_ID NUMBER(38,0) COMMENT 'Broadcast Date ID field',
	BROADCAST_DATE TIMESTAMP_NTZ(9) COMMENT 'The date on when the program is broadcasted',
	SRC_BROADCAST_NETWORK_NAME VARCHAR(255) COMMENT 'Broadcast Network Channel Name',
	SRC_PROGRAM_NAME VARCHAR(255) COMMENT 'Name of the Program',
	SRC_MARKET_BREAK VARCHAR(255) COMMENT 'Identified Market break category by the broadcast network',
	SRC_DAYPART_NAME VARCHAR(255) COMMENT 'Name of the day part when program telecasted',
	SRC_PLAYBACK_PERIOD_CD VARCHAR(200) COMMENT 'A comma separated list of data streams.',
	SRC_DEMOGRAPHIC_GROUP VARCHAR(255) COMMENT 'A comma separated list of demographic groups (e.g. Females 18 to 49 and Males 18 - 24 input as F18-49,M18-24).',
	MXM_SOURCE VARCHAR(255) COMMENT 'The source information for each feed type available for the minute by minute ratings',
	PROGRAM_TELECAST_RPT_STARTTIME VARCHAR(10) COMMENT 'Program Telecast Report Start Time',
	PROGRAM_TELECAST_RPT_ENDTIME VARCHAR(10) COMMENT 'Program Telecast Report End Time',
	MIN_OF_PGM_VALUE NUMBER(38,0) COMMENT 'Metrics for Minute of program value',
	MOST_CURRENT_AUDIENCE_AVG_PCT NUMBER(20,2) COMMENT 'Metrics for most current audience average percentage value',
	MOST_CURRENT_US_AUDIENCE_AVG_PROJ_000 NUMBER(38,0) COMMENT 'Metrics for most current US audience average projection in thousands',
	MOST_CURRENT_NW_CVG_AREA_AVG_PCT NUMBER(20,2) COMMENT 'Metrics for most current network coverage areas average percentage',
	SHOWDBID NUMBER(38,0) COMMENT 'Show DB ID to uniquely identify the lite log of the program telecasted at a time',
	TITLE VARCHAR(1000) COMMENT 'Title of the Program like NXT, RAW, SmackDown, etc.',
	SUBTITLE VARCHAR(1000) COMMENT 'Subtitle of the program',
	EPISODENUMBER VARCHAR(1000) COMMENT 'Episode Number',
	AIRDATE DATE COMMENT 'The date on when the program aired',
	INPOINT VARCHAR(50) COMMENT 'The starting time of the particular segment',
	OUTPOINT VARCHAR(50) COMMENT 'The end time of the particular segment',
	INPOINT_24HR_EST TIMESTAMP_NTZ(9) COMMENT 'The starting time of the particular segment converted to 24Hr Clock',
	MODIFIED_INPOINT TIMESTAMP_NTZ(9) COMMENT 'Modified starting time of the particular segment by round it off to closest minute',
	MODIFIED_OUTPOINT TIMESTAMP_NTZ(9) COMMENT 'Modified end time of the particular segment by round it off to closest minute',
	SEGMENTTYPE VARCHAR(200) COMMENT 'Type of Segment',
	COMMENT VARCHAR(6000) COMMENT 'The comment about the segment',
	MATCHTYPE VARCHAR(500) COMMENT 'Type of the Match',
	TALENTACTIONS VARCHAR(1000) COMMENT 'Describing the actions of talents',
	MOVE VARCHAR(200) COMMENT 'Describing the move',
	FINISHTYPE VARCHAR(500) COMMENT 'The type of finish',
	RECORDDATE DATE COMMENT 'The date on when the program recorded',
	FILEID VARCHAR(200) COMMENT 'The File ID field',
	DURATION VARCHAR(200) COMMENT 'Duration of the Segment',
	ANNOUNCERS VARCHAR(1000) COMMENT 'Announcers of the program',
	MATCHTITLE VARCHAR(500) COMMENT 'Title of the match',
	VENUELOCATION VARCHAR(100) COMMENT 'Venue Location of the Program',
	VENUENAME VARCHAR(200) COMMENT 'Venue Name of the Program',
	ISSEGMENTMARKER VARCHAR(200) COMMENT 'Segment Marker',
	LOGENTRYDBID NUMBER(38,0) COMMENT 'Log Entry DB ID Field',
	LOGENTRYGUID VARCHAR(256) COMMENT 'Log Entry Guide',
	LOGGERNAME VARCHAR(100) COMMENT 'Name of the Logger',
	LOGNAME VARCHAR(200) COMMENT 'Log Name',
	MASTERCLIPID VARCHAR(2000) COMMENT 'Master Clip ID',
	MODIFIEDDATETIME TIMESTAMP_NTZ(9) COMMENT 'Modified Date Time',
	NETWORKASSETID VARCHAR(100) COMMENT 'Network Asset ID',
	SPONSORS VARCHAR(256) COMMENT 'Sponsors of the Program',
	WEAPON VARCHAR(256) COMMENT 'Weapons used',
	SEASON VARCHAR(100) COMMENT 'Season details',
	SOURCE_FFED_NAME VARCHAR(1000) COMMENT 'source_ffed_name',
	ETL_BATCH_ID VARCHAR(26) COMMENT 'Unique ID of DBT Job used to insert the record',
	ETL_INSERT_USER_ID VARCHAR(15) COMMENT 'Unique ID of the DBT user that was used to insert the record',
	ETL_INSERT_REC_DTTM TIMESTAMP_TZ(9) COMMENT 'Date Time information on when the DBT inserted the record',
	ETL_UPDATE_USER_ID VARCHAR(1) COMMENT 'Unique ID of the DBT user which was used to update the record manually',
	ETL_UPDATE_REC_DTTM TIMESTAMP_NTZ(9) COMMENT 'Date Time information on when the record was updated',
	ADDITIONALTALENT VARCHAR(65535)
)COMMENT='## Implementation Detail\n*   Date        : 08/17/2020\n*   Version     : 1.0\n*   TableName   : rpt_nl_daily_minxmin_lite_log_ratings\n*   Schema : fds_nl\n*   Contributor : Rahul Chandran\n*   Description : Minute By Minture Ratings joining with Lite Log Report table consist of ratings of segments along with its details referencing from Minute By Minute Ratings and Lite Log tables on daily-basis\n\n## Maintenance Log\n* Date : 08/17/2020 ; Developer: Rahul Chandran ; Change: Initial Version as a part of Phase 4b Project.'
;