version: 2
models:
  - name: aggr_voc_daily_mentions_count
    description: '{{ doc("aggr_voc_daily_mentions_count") }}'
    columns:
        - name: posted_date
          description: The date on when the tweet is posted
        - name: mentions
          description: It gives detail which tweet is mentioning about
        - name: count_tweets
          description: Gives the count of total number of tweets
        - name: etl_batch_id          
          description: Unique ID of DBT Job used to insert the record
        - name: etl_insert_user_id          
          description: Unique ID of the DBT user that was used to insert the record
        - name: etl_insert_rec_dttm          
          description: Date Time information on when the DBT inserted the record
        - name: etl_update_user_id          
          description: Unique ID of the DBT user which was used to update the record manually
        - name: etl_update_rec_dttm          
          description: Date Time information on when the record was updated
  - name: vw_aggr_voc_daily_mentions_count
    description: '{{ doc("vw_aggr_voc_daily_mentions_count") }}' 
    columns:
        - name: posted_date
          description: The date on when the tweet is posted
        - name: mentions
          description: It gives detail which tweet is mentioning about
        - name: count_tweets
          description: Gives the count of total number of tweets
        - name: etl_batch_id          
          description: Unique ID of DBT Job used to insert the record
        - name: etl_insert_user_id          
          description: Unique ID of the DBT user that was used to insert the record
        - name: etl_insert_rec_dttm          
          description: Date Time information on when the DBT inserted the record
        - name: etl_update_user_id          
          description: Unique ID of the DBT user which was used to update the record manually
        - name: etl_update_rec_dttm          
          description: Date Time information on when the record was updated      