/*
*************************************************************************************************************************************************
   TableName   : rpt_weekly_domestic_tagging
   Schema	   : fds_nl
   Contributor : B.V.Sai Praveen Chakravarthy
   Description : summary table for capturing the tagged attributes of properties 
                 by performing union of all the intermediate ephemeral tables
   Version      Date             Author               Request
   1.0          03/15/2021       pchakrav             ADVA-297
*************************************************************************************************************************************************
*/


{{ config(materialized='incremental',incremental_strategy='delete+insert',
enabled = true,tags=['domestic','tagging','summary'],
unique_key= "orig_broadcast_date_id||'-'||src_broadcast_network_id||'-'||dim_nl_series_id
||'-'||dim_nl_episode_id||'-'||src_telecast_id||'-'||src_demographic_group
||'-'||src_playback_period_cd",
schema ='fds_nl',post_hook = "grant select on {{ this }} to DA_RBAVISETTY_USER_ROLE") }}

with rpt_nl_weekly_domestic_tagging AS 
    (SELECT src_broadcast_orig_date,
        broadcast_date,
        broadcast_network_name,
        src_series_name,
        src_episode_title,
         program_telecast_rpt_starttime,
        program_telecast_rpt_endtime,
         src_total_duration,
        src_playback_period_cd,
        src_demographic_group,
         src_genre_classification_cd,
        src_genre_classification_detailedtypecd,
         src_program_attributes,
        src_daypart_cd,
        src_broadcast_network_service_type,
         avg_audience_proj_000,
        avg_audience_proj_units,
        round(avg_audience_pct,
        1) AS avg_audience_pct ,
         avg_audience_pct_nw_cvg_area,
        round(share_pct) AS share_pct,
         round(share_pct_nw_cvg_area) AS share_pct_nw_cvg_area,
        telecast_trackage_name,
        DAYNAME(broadcast_date) AS calendardayofweekname,
        att_Shoulder,
        att_fights,
        att_cup,
        att_season,
        att_Channel_Qualifier,
        src_broadcast_network_id,
         orig_broadcast_date_id,
        dim_nl_series_id,
        dim_nl_episode_id,
        src_telecast_id,
         inserted_time,
        property
    FROM {{ref('intm_weekly_domestic_tagging_aew')}}
    UNION
    allSELECT src_broadcast_orig_date,
        broadcast_date,
        broadcast_network_name,
        src_series_name,
        src_episode_title,
         program_telecast_rpt_starttime,
        program_telecast_rpt_endtime,
         src_total_duration,
        src_playback_period_cd,
        src_demographic_group,
         src_genre_classification_cd,
        src_genre_classification_detailedtypecd,
         src_program_attributes,
        src_daypart_cd,
        src_broadcast_network_service_type,
         avg_audience_proj_000,
        avg_audience_proj_units,
        round(avg_audience_pct,
        1) AS avg_audience_pct ,
         avg_audience_pct_nw_cvg_area,
        round(share_pct) AS share_pct,
         round(share_pct_nw_cvg_area) AS share_pct_nw_cvg_area,
        telecast_trackage_name,
        DAYNAME(broadcast_date) AS calendardayofweekname,
        att_Shoulder,
        att_fights,
        att_cup,
        att_season,
        att_Channel_Qualifier,
        src_broadcast_network_id,
         orig_broadcast_date_id,
        dim_nl_series_id,
        dim_nl_episode_id,
        src_telecast_id,
         inserted_time,
        property
    FROM {{ref('intm_weekly_domestic_tagging_mlb')}}
    UNION
    allSELECT src_broadcast_orig_date,
        broadcast_date,
        broadcast_network_name,
        src_series_name,
        src_episode_title,
         program_telecast_rpt_starttime,
        program_telecast_rpt_endtime,
         src_total_duration,
        src_playback_period_cd,
        src_demographic_group,
         src_genre_classification_cd,
        src_genre_classification_detailedtypecd,
         src_program_attributes,
        src_daypart_cd,
        src_broadcast_network_service_type,
         avg_audience_proj_000,
        avg_audience_proj_units,
        round(avg_audience_pct,
        1) AS avg_audience_pct ,
         avg_audience_pct_nw_cvg_area,
        round(share_pct) AS share_pct,
         round(share_pct_nw_cvg_area) AS share_pct_nw_cvg_area,
        telecast_trackage_name,
        DAYNAME(broadcast_date) AS calendardayofweekname,
        att_Shoulder,
        att_fights,
        att_cup,
        att_season,
        att_Channel_Qualifier,
        src_broadcast_network_id,
         orig_broadcast_date_id,
        dim_nl_series_id,
        dim_nl_episode_id,
        src_telecast_id,
         inserted_time,
        property
    FROM {{ref('intm_weekly_domestic_tagging_nascar')}}
    UNION
    allSELECT src_broadcast_orig_date,
        broadcast_date,
        broadcast_network_name,
        src_series_name,
        src_episode_title,
         program_telecast_rpt_starttime,
        program_telecast_rpt_endtime,
         src_total_duration,
        src_playback_period_cd,
        src_demographic_group,
         src_genre_classification_cd,
        src_genre_classification_detailedtypecd,
         src_program_attributes,
        src_daypart_cd,
        src_broadcast_network_service_type,
         avg_audience_proj_000,
        avg_audience_proj_units,
        round(avg_audience_pct,
        1) AS avg_audience_pct ,
         avg_audience_pct_nw_cvg_area,
        round(share_pct) AS share_pct,
         round(share_pct_nw_cvg_area) AS share_pct_nw_cvg_area,
        telecast_trackage_name,
        DAYNAME(broadcast_date) AS calendardayofweekname,
        att_Shoulder,
        att_fights,
        att_cup,
        att_season,
        att_Channel_Qualifier,
        src_broadcast_network_id,
         orig_broadcast_date_id,
        dim_nl_series_id,
        dim_nl_episode_id,
        src_telecast_id,
         inserted_time,
        property
    FROM {{ref('intm_weekly_domestic_tagging_nba')}}
    UNION
    allSELECT src_broadcast_orig_date,
        broadcast_date,
        broadcast_network_name,
        src_series_name,
        src_episode_title,
         program_telecast_rpt_starttime,
        program_telecast_rpt_endtime,
         src_total_duration,
        src_playback_period_cd,
        src_demographic_group,
         src_genre_classification_cd,
        src_genre_classification_detailedtypecd,
         src_program_attributes,
        src_daypart_cd,
        src_broadcast_network_service_type,
         avg_audience_proj_000,
        avg_audience_proj_units,
        round(avg_audience_pct,
        1) AS avg_audience_pct ,
         avg_audience_pct_nw_cvg_area,
        round(share_pct) AS share_pct,
         round(share_pct_nw_cvg_area) AS share_pct_nw_cvg_area,
        telecast_trackage_name,
        DAYNAME(broadcast_date) AS calendardayofweekname,
        att_Shoulder,
        att_fights,
        att_cup,
        att_season,
        att_Channel_Qualifier,
        src_broadcast_network_id,
         orig_broadcast_date_id,
        dim_nl_series_id,
        dim_nl_episode_id,
        src_telecast_id,
         inserted_time,
        property
    FROM {{ref('intm_weekly_domestic_tagging_nfl')}}
    UNION
    allSELECT src_broadcast_orig_date,
        broadcast_date,
        broadcast_network_name,
        src_series_name,
        src_episode_title,
         program_telecast_rpt_starttime,
        program_telecast_rpt_endtime,
         src_total_duration,
        src_playback_period_cd,
        src_demographic_group,
         src_genre_classification_cd,
        src_genre_classification_detailedtypecd,
         src_program_attributes,
        src_daypart_cd,
        src_broadcast_network_service_type,
         avg_audience_proj_000,
        avg_audience_proj_units,
        round(avg_audience_pct,
        1) AS avg_audience_pct ,
         avg_audience_pct_nw_cvg_area,
        round(share_pct) AS share_pct,
         round(share_pct_nw_cvg_area) AS share_pct_nw_cvg_area,
        telecast_trackage_name,
        DAYNAME(broadcast_date) AS calendardayofweekname,
        att_Shoulder,
        att_fights,
        att_cup,
        att_season,
        att_Channel_Qualifier,
        src_broadcast_network_id,
         orig_broadcast_date_id,
        dim_nl_series_id,
        dim_nl_episode_id,
        src_telecast_id,
         inserted_time,
        property
    FROM {{ref('intm_weekly_domestic_tagging_nhl')}}
    UNION
    allSELECT src_broadcast_orig_date,
        broadcast_date,
        broadcast_network_name,
        src_series_name,
        src_episode_title,
         program_telecast_rpt_starttime,
        program_telecast_rpt_endtime,
         src_total_duration,
        src_playback_period_cd,
        src_demographic_group,
         src_genre_classification_cd,
        src_genre_classification_detailedtypecd,
         src_program_attributes,
        src_daypart_cd,
        src_broadcast_network_service_type,
         avg_audience_proj_000,
        avg_audience_proj_units,
        round(avg_audience_pct,
        1) AS avg_audience_pct ,
         avg_audience_pct_nw_cvg_area,
        round(share_pct) AS share_pct,
         round(share_pct_nw_cvg_area) AS share_pct_nw_cvg_area,
        telecast_trackage_name,
        DAYNAME(broadcast_date) AS calendardayofweekname,
        att_Shoulder,
        att_fights,
        att_cup,
        att_season,
        att_Channel_Qualifier,
        src_broadcast_network_id,
         orig_broadcast_date_id,
        dim_nl_series_id,
        dim_nl_episode_id,
        src_telecast_id,
         inserted_time,
        property
    FROM {{ref('intm_weekly_domestic_tagging_epl')}}
    UNION
    allSELECT src_broadcast_orig_date,
        broadcast_date,
        broadcast_network_name,
        src_series_name,
        src_episode_title,
         program_telecast_rpt_starttime,
        program_telecast_rpt_endtime,
         src_total_duration,
        src_playback_period_cd,
        src_demographic_group,
         src_genre_classification_cd,
        src_genre_classification_detailedtypecd,
         src_program_attributes,
        src_daypart_cd,
        src_broadcast_network_service_type,
         avg_audience_proj_000,
        avg_audience_proj_units,
        round(avg_audience_pct,
        1) AS avg_audience_pct ,
         avg_audience_pct_nw_cvg_area,
        round(share_pct) AS share_pct,
         round(share_pct_nw_cvg_area) AS share_pct_nw_cvg_area,
        telecast_trackage_name,
        DAYNAME(broadcast_date) AS calendardayofweekname,
        att_Shoulder,
        att_fights,
        att_cup,
        att_season,
        att_Channel_Qualifier,
        src_broadcast_network_id,
         orig_broadcast_date_id,
        dim_nl_series_id,
        dim_nl_episode_id,
        src_telecast_id,
         inserted_time,
        property
    FROM {{ref('intm_weekly_domestic_tagging_bundesliga')}}
    UNION
    allSELECT src_broadcast_orig_date,
        broadcast_date,
        broadcast_network_name,
        src_series_name,
        src_episode_title,
         program_telecast_rpt_starttime,
        program_telecast_rpt_endtime,
         src_total_duration,
        src_playback_period_cd,
        src_demographic_group,
         src_genre_classification_cd,
        src_genre_classification_detailedtypecd,
         src_program_attributes,
        src_daypart_cd,
        src_broadcast_network_service_type,
         avg_audience_proj_000,
        avg_audience_proj_units,
        round(avg_audience_pct,
        1) AS avg_audience_pct ,
         avg_audience_pct_nw_cvg_area,
        round(share_pct) AS share_pct,
         round(share_pct_nw_cvg_area) AS share_pct_nw_cvg_area,
        telecast_trackage_name,
        DAYNAME(broadcast_date) AS calendardayofweekname,
        att_Shoulder,
        att_fights,
        att_cup,
        att_season,
        att_Channel_Qualifier,
        src_broadcast_network_id,
         orig_broadcast_date_id,
        dim_nl_series_id,
        dim_nl_episode_id,
        src_telecast_id,
         inserted_time,
        property
    FROM {{ref('intm_weekly_domestic_tagging_mls')}}
    UNION
    allSELECT src_broadcast_orig_date,
        broadcast_date,
        broadcast_network_name,
        src_series_name,
        src_episode_title,
         program_telecast_rpt_starttime,
        program_telecast_rpt_endtime,
         src_total_duration,
        src_playback_period_cd,
        src_demographic_group,
         src_genre_classification_cd,
        src_genre_classification_detailedtypecd,
         src_program_attributes,
        src_daypart_cd,
        src_broadcast_network_service_type,
         avg_audience_proj_000,
        avg_audience_proj_units,
        round(avg_audience_pct,
        1) AS avg_audience_pct ,
         avg_audience_pct_nw_cvg_area,
        round(share_pct) AS share_pct,
         round(share_pct_nw_cvg_area) AS share_pct_nw_cvg_area,
        telecast_trackage_name,
        DAYNAME(broadcast_date) AS calendardayofweekname,
        att_Shoulder,
        att_fights,
        att_cup,
        att_season,
        att_Channel_Qualifier,
        src_broadcast_network_id,
         orig_broadcast_date_id,
        dim_nl_series_id,
        dim_nl_episode_id,
        src_telecast_id,
         inserted_time,
        property
    FROM {{ref('intm_weekly_domestic_tagging_ncaa')}}
    UNION
    allSELECT src_broadcast_orig_date,
        broadcast_date,
        broadcast_network_name,
        src_series_name,
        src_episode_title,
         program_telecast_rpt_starttime,
        program_telecast_rpt_endtime,
         src_total_duration,
        src_playback_period_cd,
        src_demographic_group,
         src_genre_classification_cd,
        src_genre_classification_detailedtypecd,
         src_program_attributes,
        src_daypart_cd,
        src_broadcast_network_service_type,
         avg_audience_proj_000,
        avg_audience_proj_units,
        round(avg_audience_pct,
        1) AS avg_audience_pct ,
         avg_audience_pct_nw_cvg_area,
        round(share_pct) AS share_pct,
         round(share_pct_nw_cvg_area) AS share_pct_nw_cvg_area,
        telecast_trackage_name,
        DAYNAME(broadcast_date) AS calendardayofweekname,
        att_Shoulder,
        att_fights,
        att_cup,
        att_season,
        att_Channel_Qualifier,
        src_broadcast_network_id,
         orig_broadcast_date_id,
        dim_nl_series_id,
        dim_nl_episode_id,
        src_telecast_id,
         inserted_time,
        property
    FROM {{ref('intm_weekly_domestic_tagging_open_championship')}}
    UNION
    allSELECT src_broadcast_orig_date,
        broadcast_date,
        broadcast_network_name,
        src_series_name,
        src_episode_title,
         program_telecast_rpt_starttime,
        program_telecast_rpt_endtime,
         src_total_duration,
        src_playback_period_cd,
        src_demographic_group,
         src_genre_classification_cd,
        src_genre_classification_detailedtypecd,
         src_program_attributes,
        src_daypart_cd,
        src_broadcast_network_service_type,
         avg_audience_proj_000,
        avg_audience_proj_units,
        round(avg_audience_pct,
        1) AS avg_audience_pct ,
         avg_audience_pct_nw_cvg_area,
        round(share_pct) AS share_pct,
         round(share_pct_nw_cvg_area) AS share_pct_nw_cvg_area,
        telecast_trackage_name,
        DAYNAME(broadcast_date) AS calendardayofweekname,
        att_Shoulder,
        att_fights,
        att_cup,
        att_season,
        att_Channel_Qualifier,
        src_broadcast_network_id,
         orig_broadcast_date_id,
        dim_nl_series_id,
        dim_nl_episode_id,
        src_telecast_id,
         inserted_time,
        property
    FROM {{ref('intm_weekly_domestic_tagging_pfl')}}
    UNION
    allSELECT src_broadcast_orig_date,
        broadcast_date,
        broadcast_network_name,
        src_series_name,
        src_episode_title,
         program_telecast_rpt_starttime,
        program_telecast_rpt_endtime,
         src_total_duration,
        src_playback_period_cd,
        src_demographic_group,
         src_genre_classification_cd,
        src_genre_classification_detailedtypecd,
         src_program_attributes,
        src_daypart_cd,
        src_broadcast_network_service_type,
         avg_audience_proj_000,
        avg_audience_proj_units,
        round(avg_audience_pct,
        1) AS avg_audience_pct ,
         avg_audience_pct_nw_cvg_area,
        round(share_pct) AS share_pct,
         round(share_pct_nw_cvg_area) AS share_pct_nw_cvg_area,
        telecast_trackage_name,
        DAYNAME(broadcast_date) AS calendardayofweekname,
        att_Shoulder,
        att_fights,
        att_cup,
        att_season,
        att_Channel_Qualifier,
        src_broadcast_network_id,
         orig_broadcast_date_id,
        dim_nl_series_id,
        dim_nl_episode_id,
        src_telecast_id,
         inserted_time,
        property
    FROM {{ref('intm_weekly_domestic_tagging_pga')}}
    UNION
    allSELECT src_broadcast_orig_date,
        broadcast_date,
        broadcast_network_name,
        src_series_name,
        src_episode_title,
         program_telecast_rpt_starttime,
        program_telecast_rpt_endtime,
         src_total_duration,
        src_playback_period_cd,
        src_demographic_group,
         src_genre_classification_cd,
        src_genre_classification_detailedtypecd,
         src_program_attributes,
        src_daypart_cd,
        src_broadcast_network_service_type,
         avg_audience_proj_000,
        avg_audience_proj_units,
        round(avg_audience_pct,
        1) AS avg_audience_pct ,
         avg_audience_pct_nw_cvg_area,
        round(share_pct) AS share_pct,
         round(share_pct_nw_cvg_area) AS share_pct_nw_cvg_area,
        telecast_trackage_name,
        DAYNAME(broadcast_date) AS calendardayofweekname,
        att_Shoulder,
        att_fights,
        att_cup,
        att_season,
        att_Channel_Qualifier,
        src_broadcast_network_id,
         orig_broadcast_date_id,
        dim_nl_series_id,
        dim_nl_episode_id,
        src_telecast_id,
         inserted_time,
        property
    FROM {{ref('intm_weekly_domestic_tagging_premier_boxing')}}
    UNION
    allSELECT src_broadcast_orig_date,
        broadcast_date,
        broadcast_network_name,
        src_series_name,
        src_episode_title,
         program_telecast_rpt_starttime,
        program_telecast_rpt_endtime,
         src_total_duration,
        src_playback_period_cd,
        src_demographic_group,
         src_genre_classification_cd,
        src_genre_classification_detailedtypecd,
         src_program_attributes,
        src_daypart_cd,
        src_broadcast_network_service_type,
         avg_audience_proj_000,
        avg_audience_proj_units,
        round(avg_audience_pct,
        1) AS avg_audience_pct ,
         avg_audience_pct_nw_cvg_area,
        round(share_pct) AS share_pct,
         round(share_pct_nw_cvg_area) AS share_pct_nw_cvg_area,
        telecast_trackage_name,
        DAYNAME(broadcast_date) AS calendardayofweekname,
        att_Shoulder,
        att_fights,
        att_cup,
        att_season,
        att_Channel_Qualifier,
        src_broadcast_network_id,
         orig_broadcast_date_id,
        dim_nl_series_id,
        dim_nl_episode_id,
        src_telecast_id,
         inserted_time,
        property
    FROM {{ref('intm_weekly_domestic_tagging_rydercup')}}
    UNION
    allSELECT src_broadcast_orig_date,
        broadcast_date,
        broadcast_network_name,
        src_series_name,
        src_episode_title,
         program_telecast_rpt_starttime,
        program_telecast_rpt_endtime,
         src_total_duration,
        src_playback_period_cd,
        src_demographic_group,
         src_genre_classification_cd,
        src_genre_classification_detailedtypecd,
         src_program_attributes,
        src_daypart_cd,
        src_broadcast_network_service_type,
         avg_audience_proj_000,
        avg_audience_proj_units,
        round(avg_audience_pct,
        1) AS avg_audience_pct ,
         avg_audience_pct_nw_cvg_area,
        round(share_pct) AS share_pct,
         round(share_pct_nw_cvg_area) AS share_pct_nw_cvg_area,
        telecast_trackage_name,
        DAYNAME(broadcast_date) AS calendardayofweekname,
        att_Shoulder,
        att_fights,
        att_cup,
        att_season,
        att_Channel_Qualifier,
        src_broadcast_network_id,
         orig_broadcast_date_id,
        dim_nl_series_id,
        dim_nl_episode_id,
        src_telecast_id,
         inserted_time,
        property
    FROM {{ref('intm_weekly_domestic_tagging_top_rank_boxing')}}
    UNION
    allSELECT src_broadcast_orig_date,
        broadcast_date,
        broadcast_network_name,
        src_series_name,
        src_episode_title,
         program_telecast_rpt_starttime,
        program_telecast_rpt_endtime,
         src_total_duration,
        src_playback_period_cd,
        src_demographic_group,
         src_genre_classification_cd,
        src_genre_classification_detailedtypecd,
         src_program_attributes,
        src_daypart_cd,
        src_broadcast_network_service_type,
         avg_audience_proj_000,
        avg_audience_proj_units,
        round(avg_audience_pct,
        1) AS avg_audience_pct ,
         avg_audience_pct_nw_cvg_area,
        round(share_pct) AS share_pct,
         round(share_pct_nw_cvg_area) AS share_pct_nw_cvg_area,
        telecast_trackage_name,
        DAYNAME(broadcast_date) AS calendardayofweekname,
        att_Shoulder,
        att_fights,
        att_cup,
        att_season,
        att_Channel_Qualifier,
        src_broadcast_network_id,
         orig_broadcast_date_id,
        dim_nl_series_id,
        dim_nl_episode_id,
        src_telecast_id,
         inserted_time,
        property
    FROM {{ref('intm_weekly_domestic_tagging_uefa')}}
    UNION
    allSELECT src_broadcast_orig_date,
        broadcast_date,
        broadcast_network_name,
        src_series_name,
        src_episode_title,
         program_telecast_rpt_starttime,
        program_telecast_rpt_endtime,
         src_total_duration,
        src_playback_period_cd,
        src_demographic_group,
         src_genre_classification_cd,
        src_genre_classification_detailedtypecd,
         src_program_attributes,
        src_daypart_cd,
        src_broadcast_network_service_type,
         avg_audience_proj_000,
        avg_audience_proj_units,
        round(avg_audience_pct,
        1) AS avg_audience_pct ,
         avg_audience_pct_nw_cvg_area,
        round(share_pct) AS share_pct,
         round(share_pct_nw_cvg_area) AS share_pct_nw_cvg_area,
        telecast_trackage_name,
        DAYNAME(broadcast_date) AS calendardayofweekname,
        att_Shoulder,
        att_fights,
        att_cup,
        att_season,
        att_Channel_Qualifier,
        src_broadcast_network_id,
         orig_broadcast_date_id,
        dim_nl_series_id,
        dim_nl_episode_id,
        src_telecast_id,
         inserted_time,
        property
    FROM {{ref('intm_weekly_domestic_tagging_ufc')}}
    UNION
    allSELECT src_broadcast_orig_date,
        broadcast_date,
        broadcast_network_name,
        src_series_name,
        src_episode_title,
         program_telecast_rpt_starttime,
        program_telecast_rpt_endtime,
         src_total_duration,
        src_playback_period_cd,
        src_demographic_group,
         src_genre_classification_cd,
        src_genre_classification_detailedtypecd,
         src_program_attributes,
        src_daypart_cd,
        src_broadcast_network_service_type,
         avg_audience_proj_000,
        avg_audience_proj_units,
        round(avg_audience_pct,
        1) AS avg_audience_pct ,
         avg_audience_pct_nw_cvg_area,
        round(share_pct) AS share_pct,
         round(share_pct_nw_cvg_area) AS share_pct_nw_cvg_area,
        telecast_trackage_name,
        DAYNAME(broadcast_date) AS calendardayofweekname,
        att_Shoulder,
        att_fights,
        att_cup,
        att_season,
        att_Channel_Qualifier,
        src_broadcast_network_id,
         orig_broadcast_date_id,
        dim_nl_series_id,
        dim_nl_episode_id,
        src_telecast_id,
         inserted_time,
        property
    FROM {{ref('intm_weekly_domestic_tagging_uot')}}
    UNION
    allSELECT src_broadcast_orig_date,
        broadcast_date,
        broadcast_network_name,
        src_series_name,
        src_episode_title,
         program_telecast_rpt_starttime,
        program_telecast_rpt_endtime,
         src_total_duration,
        src_playback_period_cd,
        src_demographic_group,
         src_genre_classification_cd,
        src_genre_classification_detailedtypecd,
         src_program_attributes,
        src_daypart_cd,
        src_broadcast_network_service_type,
         avg_audience_proj_000,
        avg_audience_proj_units,
        round(avg_audience_pct,
        1) AS avg_audience_pct ,
         avg_audience_pct_nw_cvg_area,
        round(share_pct) AS share_pct,
         round(share_pct_nw_cvg_area) AS share_pct_nw_cvg_area,
        telecast_trackage_name,
        DAYNAME(broadcast_date) AS calendardayofweekname,
        att_Shoulder,
        att_fights,
        att_cup,
        att_season,
        att_Channel_Qualifier,
        src_broadcast_network_id,
         orig_broadcast_date_id,
        dim_nl_series_id,
        dim_nl_episode_id,
        src_telecast_id,
         inserted_time,
        property
    FROM {{ref('intm_weekly_domestic_tagging_usopengolf')}}
    UNION
    allSELECT src_broadcast_orig_date,
        broadcast_date,
        broadcast_network_name,
        src_series_name,
        src_episode_title,
         program_telecast_rpt_starttime,
        program_telecast_rpt_endtime,
         src_total_duration,
        src_playback_period_cd,
        src_demographic_group,
         src_genre_classification_cd,
        src_genre_classification_detailedtypecd,
         src_program_attributes,
        src_daypart_cd,
        src_broadcast_network_service_type,
         avg_audience_proj_000,
        avg_audience_proj_units,
        round(avg_audience_pct,
        1) AS avg_audience_pct ,
         avg_audience_pct_nw_cvg_area,
        round(share_pct) AS share_pct,
         round(share_pct_nw_cvg_area) AS share_pct_nw_cvg_area,
        telecast_trackage_name,
        DAYNAME(broadcast_date) AS calendardayofweekname,
        att_Shoulder,
        att_fights,
        att_cup,
        att_season,
        att_Channel_Qualifier,
        src_broadcast_network_id,
         orig_broadcast_date_id,
        dim_nl_series_id,
        dim_nl_episode_id,
        src_telecast_id,
         inserted_time,
        property
    FROM {{ref('intm_weekly_domestic_tagging_wimbledon')}} )
SELECT src_broadcast_orig_date,
        broadcast_date,
        broadcast_network_name,
        src_series_name,
        src_episode_title,
         program_telecast_rpt_starttime,
        program_telecast_rpt_endtime,
         src_total_duration,
        src_playback_period_cd,
        src_demographic_group,
         src_genre_classification_cd,
        src_genre_classification_detailedtypecd,
         src_program_attributes,
        src_daypart_cd,
        src_broadcast_network_service_type,
         avg_audience_proj_000,
        avg_audience_proj_units,
        round(avg_audience_pct,
        1) AS avg_audience_pct ,
         avg_audience_pct_nw_cvg_area,
        round(share_pct) AS share_pct,
         round(share_pct_nw_cvg_area) AS share_pct_nw_cvg_area,
        telecast_trackage_name,
        DAYNAME(broadcast_date) AS calendardayofweekname,
        att_Shoulder,
        att_fights,
        att_cup,
        att_season,
        att_Channel_Qualifier,
        src_broadcast_network_id,
         orig_broadcast_date_id,
        dim_nl_series_id,
        dim_nl_episode_id,
        src_telecast_id,
         inserted_time,
        property,
        id,
        ROWNUMBER
FROM 
    (SELECT src_broadcast_orig_date,
        broadcast_date,
        broadcast_network_name,
        src_series_name,
        src_episode_title,
         program_telecast_rpt_starttime,
        program_telecast_rpt_endtime,
         src_total_duration,
        src_playback_period_cd,
        src_demographic_group,
         src_genre_classification_cd,
        src_genre_classification_detailedtypecd,
         src_program_attributes,
        src_daypart_cd,
        src_broadcast_network_service_type,
         avg_audience_proj_000,
        avg_audience_proj_units,
        round(avg_audience_pct,
        1) AS avg_audience_pct ,
         avg_audience_pct_nw_cvg_area,
        round(share_pct) AS share_pct,
         round(share_pct_nw_cvg_area) AS share_pct_nw_cvg_area,
        telecast_trackage_name,
        DAYNAME(broadcast_date) AS calendardayofweekname,
        att_Shoulder,
        att_fights,
        att_cup,
        att_season,
        att_Channel_Qualifier,
        src_broadcast_network_id,
         orig_broadcast_date_id,
        dim_nl_series_id,
        dim_nl_episode_id,
        src_telecast_id,
         inserted_time,
        property,
         orig_broadcast_date_id||'-'||src_broadcast_network_id||'-'||dim_nl_series_id ||'-'||dim_nl_episode_id||'-'||src_telecast_id||'-'||src_demographic_group ||'-'||src_playback_period_cd AS id, ROW_NUMBER()
        OVER (partition by orig_broadcast_date_id, src_broadcast_network_id, dim_nl_series_id, dim_nl_episode_id, src_telecast_id, src_demographic_group, src_playback_period_cd
    ORDER BY  inserted_time desc) ROWNUMBER
    FROM rpt_nl_weekly_domestic_tagging )
WHERE ROWNUMBER =1 {% if is_incremental() %}
HAVING inserted_time > 
    (SELECT max(inserted_time)
    FROM {{ this }}) {% endif %} 