version: 2
models:
  - name: vw_rpt_daily_tw_published_post
    description: '{{ doc("vw_rpt_daily_tw_published_post") }}'
    columns:
        - name: dim_smprovider_account_id
          description: Unique Identifier of the social media provider account id
        - name: dim_social_account_id
          description: Unique Identifier of the social account id
        - name: dim_platform_id
          description: Unique Identifier of the social media platform id
        - name: dim_video_id
          description: Unique Identifier of the social media video id
        - name: dim_media_id
          description: Unique Identifier of the social media id
        - name: dim_content_type_id
          description: Unique Identifier of the content type published on social media
        - name: dim_date_id
          description: Unique Identifier of the social media data received date from the provider
        - name: date_posted
          description: Date video posted 
        - name: tweet
          description: Description of tweet
        - name: content_publish_time_secs
          description: content published post time seconds
        - name: as_on_date
          description: Record as-on date