CREATE TABLE AGGR_KNTR_WEEKLY_COMPETITIVE_PROGRAM_RATINGS (
	WEEK_START_DATE DATE COMMENT 'Calendar Year Week Start Date based on Broadcast Date',
	WEEK_END_DATE DATE COMMENT 'Calendar Year Week End Date based on Broadcast Date',
	WEEK_NUM NUMBER(38,0) COMMENT 'Calendar Year Week Number based on Broadcast Date',
	MONTH VARCHAR(11) COMMENT 'Abbreviated Month Name based on week start date',
	QUARTER VARCHAR(12) COMMENT 'Abbreviated Quarter Name based on week start date',
	YEAR NUMBER(38,0) COMMENT 'Year based on week start date',
	SRC_COUNTRY VARCHAR(255) COMMENT 'country name where competitive program telecasted',
	SRC_CHANNEL VARCHAR(255) COMMENT 'The channel name in which competitive program telecasted',
	SRC_PROPERTY VARCHAR(255) COMMENT 'The competitive program which is telecasted',
	DEMOGRAPHIC VARCHAR(255) COMMENT 'The demographic group who watched the competitive program',
	HD_FLAG VARCHAR(3) COMMENT 'Indicates whether the channel is HD or not',
	TOTAL_DURATION_MINS NUMBER(38,2) COMMENT 'The total duration of the competitive program in minutes',
	DURATION_HOURS NUMBER(38,5) COMMENT 'The total duration of the competitive program in hours',
	RAT_VALUE NUMBER(38,4) COMMENT 'The rating value of the competitive program',
	VIEWING_HOURS NUMBER(38,8) COMMENT 'The viewing hours of competitive program by specified demographic group',
	TELECASTS_COUNT NUMBER(38,0) COMMENT 'Count of Telecasts of competitive program',
	WEEKLY_CUMULATIVE_AUDIENCE NUMBER(38,3) COMMENT 'The weekly cumulative Audience who watched the competitive program',
	ETL_BATCH_ID VARCHAR(26) COMMENT 'Unique ID of DBT Job used to insert the record',
	ETL_INSERT_USER_ID VARCHAR(15) COMMENT 'Unique ID of the DBT user that was used to insert the record',
	ETL_INSERT_REC_DTTM TIMESTAMP_TZ(9) COMMENT 'Date Time information on when the DBT inserted the record',
	ETL_UPDATE_USER_ID VARCHAR(1) COMMENT 'Unique ID of the DBT user which was used to update the record manually',
	ETL_UPDATE_REC_DTTM TIMESTAMP_NTZ(9) COMMENT 'Date Time information on when the record was updated'
)COMMENT='## Implementation Detail\n*   Date        : 07/24/2020\n*   Version     : 1.0\n*   TableName   : aggr_kntr_weekly_competitive_program_ratings\n*   Schema     : fds_kntr\n*   Contributor : Rahul Chandran\n*   Description : Competitive Program Ratings Weekly Aggregate Table consist of rating details of competitive programs referencing from Annual Profile Table on weekly-basis\n\n## Maintenance Log\n* Date : 07/24/2020 ; Developer: Rahul Chandran ; Change: Initial Version as a part of Phase 4b Project.'
;