{{
  config({
		'schema': 'fds_nl',
		"materialized": 'table','tags': "Phase 4B",
		"persist_docs": {'relation' : true, 'columns' : true}
  })
}}
SELECT
    broadcast_date_id,
    broadcast_date,
    src_broadcast_network_name,
    src_program_name,
    src_market_break,
    src_daypart_name,
    src_playback_period_cd,
    src_demographic_group,
    mxm_source,
    program_telecast_rpt_starttime,
    program_telecast_rpt_endtime,
    min_of_pgm_value,
    most_current_audience_avg_pct,
    most_current_us_audience_avg_proj_000,
    most_current_nw_cvg_area_avg_pct,
    showdbid,
    title,
    subtitle,
    episodenumber,
    airdate,
    inpoint,
    outpoint,
    inpoint_24hr_est,
    modified_inpoint_1  AS modified_inpoint,
    modified_outpoint_1 AS modified_outpoint,
    segmenttype,
    comment,
    matchtype,
    talentactions,
    move,
    finishtype,
    recorddate,
    fileid,
    duration,
    additionaltalent,
    announcers,
    matchtitle,
    venuelocation,
    venuename,
    issegmentmarker,
    logentrydbid,
    logentryguid,
    loggername,
    logname,
    masterclipid,
    modifieddatetime,
    networkassetid,
    sponsors,
    weapon,
    season,
    source_ffed_name,
	commercial_overlap_ind,
    ('DBT_' || to_char(sysdate, 'YYYY_MM_DD_HH_MI_SS') || '_5A') as etl_batch_id,
    'bi_dbt_user_prd'                                            as etl_insert_user_id,
    sysdate                                                      as etl_insert_rec_dttm,
    cast(null as varchar(15))                                    as etl_update_user_id,
    cast(null as timestamp)                                      as etl_update_rec_dttm
FROM
    {{ref('intm_nl_daily_lite_log_ratings')}}