CREATE TABLE RPT_NL_DAILY_WWE_LIVE_COMMERCIAL_RATINGS (
	BROADCAST_DATE_ID NUMBER(38,0) COMMENT 'Broadcast Date ID field',
	BROADCAST_DATE TIMESTAMP_NTZ(9) COMMENT 'Derived dates based on the viewing period; before 6 am morning hours is the previous date broadcast hour',
	BROADCAST_MONTH_NUM NUMBER(38,0) COMMENT 'Broadcast Month Number',
	BROADCAST_MONTH_NM VARCHAR(20) COMMENT 'Broadcast Month abbr name',
	BROADCAST_QUARTER_NUM NUMBER(38,0) COMMENT 'Broadcast Quarter number',
	BROADCAST_QUARTER_NM VARCHAR(20) COMMENT 'broadcast Quarter Name',
	BROADCAST_YEAR NUMBER(38,0) COMMENT 'Broadcast year',
	SRC_BROADCAST_NETWORK_ID VARCHAR(200) COMMENT 'A unique numerical identifier for an individual programming originator.',
	SRC_PLAYBACK_PERIOD_CD VARCHAR(200) COMMENT 'A comma separated list of data streams. Time-shifted viewing from DVR Playback or On-demand content with the same commercial load.• Live (Live - Includes viewing that occurred during the live airing).• Live+SD (Live + Same Day -Includes all playback that occurred within the same day of the liveairing).• Live+3 (Live + 3 Days - Includes all playback that occurred within three days of the live airing).• Live+7 (Live + 7 Days - Includes all playback that occurred within seven days of the live airing).',
	SRC_DEMOGRAPHIC_GROUP VARCHAR(255) COMMENT 'A comma separated list of demographic groups (e.g. Females 18 to 49 and Males 18 - 24 input as F18-49,M18-24).',
	SRC_PROGRAM_ID VARCHAR(255) COMMENT 'A unique numerical identifier for an individual program name.',
	PROGRAM_TELECAST_RPT_STARTTIME VARCHAR(10) COMMENT 'The start time of the program telecast (HH:MM).',
	PROGRAM_TELECAST_RPT_ENDTIME VARCHAR(10) COMMENT 'The end time of the program telecast (HH:MM).',
	AVG_VIEWING_HOURS_UNITS NUMBER(38,0) COMMENT 'Derived Average Viewing Hours in minutes',
	NATL_COMM_CLOCKMTS_AVG_AUDIENCE_PROJ_000 NUMBER(38,0) COMMENT 'National Commercial Clock Minute Average Audience Projection (000) (The projected number of households tuned or persons viewing the average qualified commercial minute of the selected program within the total U.S., expressed in thousands.)',
	NATL_COMM_CLOCKMTS_AVG_AUDIENCE_PROJ_PCT NUMBER(20,2) COMMENT 'National Commercial Clock Minute Average Audience Percentage (The percentage of the target demographic viewing the average qualified commercial minute of the selected program within the total U.S.)',
	NATL_COMM_CLOCKMTS_CVG_AREA_AVG_AUDIENCE_PROJ_PCT NUMBER(20,2) COMMENT 'National Commercial Clock Minute Coverage Area Average Audience Percent (The percentage of the target demographic viewing the average qualified commercial minute of a selected program within a network’s coverage area.)',
	NATL_COMM_CLOCKMTS_DURATION NUMBER(38,0) COMMENT 'National Commerical Clock Minutes Duration (seconds) (The total number of seconds across qualified commercial minutes within a selected program.)',
	ETL_BATCH_ID VARCHAR(100),
	ETL_INSERT_USER_ID VARCHAR(100),
	ETL_INSERT_REC_DTTM TIMESTAMP_NTZ(9),
	ETL_UPDATE_USER_ID VARCHAR(50),
	ETL_UPDATE_REC_DTTM TIMESTAMP_NTZ(9)
)COMMENT='## Implementation Detail\n* Date        : 06/12/2020\n* Version     : 1.0\n* TableName   : rpt_nl_daily_wwe_live_commercial_ratings\n* Schema   : fds_nl\n* Contributor : Rahul Chandran\n* Description : WWE Live Commercial Ratings Daily Report table consist of rating details of all WWE Live - RAW, SD, NXT Programs referencing from Commercial Viewership Ratings table on daily-basis\n\n## Schedule Details\n* Frequency : Weekly ; 04:00 A.M EST (Tue)\n* Dependent Jobs (process_name ; process_id) : t_di_nielsen_fact_nl_commercial_viewership_ratings_abac ; 12132 (Tue) \n\n## Maintenance Log\n* Date : 06/12/2020 ; Developer: Rahul Chandran ; Change: Initial Version as a part of Phase 4b Project.\n* Date : 09/21/2020 ; Developer: Remya K Nair   ; Change: Added columns program_telecast_rpt_starttime,program_telecast_rpt_endtime as a part of Phase 4b Project.'
;