version: 2
models:
  - name: vw_aggr_daily_network_adds_and_loss_track
    description: A view to display total subscription losses of orders
    columns:
        - name: date
          description: Processing Date
        - name: country
          description: Country of the product sku is purchased
        - name: order_status
          description: The status of order whether it is 'trial' or 'paid'
        - name: cancel_type
          description: Type of cancellation whether it is 'Voluntary' or 'Involuntary'
        - name: payment_method
          description: Payment method used for the payment
        - name: payments_count
          description: Total number of payments done for the orders
        - name: total_losses
          description: The total number of subscription order losses
  - name: vw_aggr_monthly_network_perf_renewal_payment_track
    description: A view to display various metrics of order subscriptions
    columns:
        - name: billing_month
          description: Original Billing Month
        - name: original_billing_date
          description: Original Billing Date
        - name: order_status
          description: The status of order whether it is 'trial' or 'paid'
        - name: country
          description: Country where payment is billed
        - name: payment_type
          description: Payment method used for the payment
        - name: renewed_count
          description: The number of payments done for the orders
        - name: hard_fail_indicator
          description: Type of cancellation whether it is 'Voluntary' or 'Involuntary'
        - name: renewed_total
          description: The number of subscription orders up for renewal 
        - name: involuntary_cancels_count
          description: The number of inactive voluntary cancelled order subscriptions with same original and scheduled billing date
        - name: voluntary_cancels_count
          description: The number of renewed subscription orders
        - name: soft_fail_enter
          description: The number of inactive involuntary cancelled order subscriptions
        - name: soft_fail_successful_enter
          description: The number of inactive voluntary cancelled order subscriptions
        - name: payments_count
          description: The number of soft fail enter (scheduled billing date > original billing date) order subscriptions
        - name: cancel_type
        
  - name: vw_aggr_nplus_ppv_week_adds_tracking
    description:  '{{ doc("vw_aggr_nplus_ppv_week_adds_tracking") }}'
    columns:
        - name: event_date
          description: Date and timestamp of the scheduled live events as received from LES
        - name: ppv_event_nm
          description: Name of the PPVevent
        - name: ppv_nm
          description: Name of the PPV
        - name: ghw_start_date
          description: date of Event Date minus 6 days
        - name: ghw_end_date
          description: date of Event date plus 2 days
        - name: year
          description: Extracted year from event date
        - name: event
          description: concatenated text of PPV event name and year 
        - name: full_date
          description: full date
        - name: daily_paid_adds_cnt
          description: Daily count of paid subscriber adds
        - name: daily_trial_adds_cnt
          description: Daily count of trial subscriber adds
        - name: daily_promo_paid_add_cnt
          description: Daily count of total promo paid subscription add
        - name: daily_paid_adds_cnt_new
          description: custom filed based on order type and Daily count of paid subscriber adds
        - name: daily_paid_adds_cnt_winback
          description: custom filed based on order type winback and Daily count of paid subscriber adds
        - name: bill_date
          description: Process date
        - name: forecast_paid_winbacks
          description: Roll up of all paid winback subscriptions for the day
        - name: forecast_new_paid
          description: Roll up of all paid subscriptions who have paid for the first time
        - name: forecast_free_trial_subs
          description: Total trial adds for the day

  - name: rpt_network_ppv_actuals_estimates_forecast
    description: ppv forecast information 
    columns:
        - name: event_date
          description: PPV event date
        - name: event_dttm
          description: PPV event date and time
        - name: event_name
          description: PPV event name
        - name: event_type
          description: Evenet type
        - name: event_reporting_type
          description: Event reporting type
        - name: adds_days_to_event
          description: adds day to event
        - name: adds_day_of_week
          description: adds day of the week
        - name: adds_date
          description: adds date
        - name: adds_time_to_event
          description: adds time to event
        - name: adds_time
          description: adds time
        - name: paid_adds
          description: paid adds
        - name: trial_adds
          description: trial adds
        - name: total_adds
          description: total adds
        - name: current_event_reporting_type
          description: current event reporting type
        - name: current_event_name
          description: current event name
        - name: current_event_date
          description: current event date
        - name: current_event_dttm
          description: current event date time
        - name: current_adds_date
          description: current adds date
        - name: current_adds_days_to_event
          description: current adds days to event
        - name: current_adds_day_of_week
          description: current adds day of the week
        - name: current_adds_time
          description: current adds time
        - name: ghw_adds_tillnow
          description: go home eek adds till now
        - name: ghw_adds_estimate
          description: go week home adds estimate
        - name: currentday_adds_tillnow
          description: currentday adds till now
        - name: currentday_adds_estimate
          description: current day adds estimate
        - name: weekend_adds_tillnow
          description: weekend adds till now
        - name: weekend_adds_estimate
          description: weekends adds estimate
        - name: current_day_forecast
          description: current day forecast
        - name: weekend_forecast
          description: weekend forecast
  - name: vw_rpt_network_daily_subscription_kpis
    description: '{{ doc("vw_rpt_network_daily_subscription_kpis") }}'
    columns:
        - name: country_nm
          description: Name of the country where the region located
        - name: date
          description: as on date of one day before
        - name: dim_country_id
          description: References dim country for region country location
        - name: country_cd
          description: Country Code
        - name: daily_paid_adds_cnt_new
          description: Daily count of paid subscriber adds where order type = 'first'
        - name: daily_paid_adds_cnt_winback
          description: Daily count of paid subscriber adds where order type = 'winback'
        - name: daily_paid_loss_cnt_new
          description: Daily count of total paid subscriber loss where order type = 'first' and payment method is not license partner
        - name: daily_paid_loss_cnt_winback
          description: Daily count of total paid subscriber loss where order type = 'winback' and payment method is not license partner
        - name: domest_paid_add
          description: Daily count of paid subscriber adds in US
        - name: domest_trial_add
          description: Daily count of trial subscriber adds in US
        - name: inter_paid_add
          description: Daily count of paid subscriber adds international
        - name: inter_trial_add
          description: Daily count of trial subscriber adds international
        - name: lp_adds
          description: Daily count of new subscriber adds for license partners
        - name: adds
          description: Daily count of new subscriber adds
        - name: domest_paid_loss
          description: Daily count of total paid subscriber loss in US and payment method is not license partner
        - name: domest_trial_loss
          description: Daily count of total trial subscriber loss in US and payment method is not license partner
        - name: inter_paid_loss
          description: Daily count of total paid subscriber loss international and payment method is not license partner
        - name: inter_trial_loss
          description: Daily count of total trial subscriber loss international and payment method is not license partner
        - name: lp_loss
          description: Daily count of total subscriber loss for license partners
        - name: loss
          description: Daily count of total subscriber loss
        - name: tier2_new_registrations
          description: daily tier2 prospect loggedin new users count
        - name: unique_visitors_daily_prospects_inactives
          description: daily unique visitors tier2 count
        - name: unique_visitors_network_subscribers_daily
          description: daily unique visitors tier3 count
        - name: domest_paid_active
          description: total number of paid active subscriptions in US
        - name: domest_trial_active
          description: total number of trial active subscriptions in US
        - name: inter_paid_active
          description: total number of paid active subscriptions international
        - name: inter_trial_active
          description: total number of trial active subscriptions international         
        - name: lp_active
          description: Total active subscription for license partners
        - name: active
          description: Total active subscriptions
        - name: inactive
          description: Total inactive subscriptions
        - name: t2_inact_dedup
          description: Count of distinct exid when tier_status = T2 and ever_active = 1 and remove_guid = 0
        - name: t2_inact_dedup_logged_in
          description: Count of distinct exid when tier_status = T2 and ever_active = 0  andlast_login_date is not null and remove_guid = 0
        - name: prospects_logged_in
          description: total tier 2 prospects who have logged in post n2.0 launch
        - name: prospects_not_logged_in
          description: total tier 2 users who have not logged in n2.0
        - name: unique_visitors_mtd_prospects_inactives
          description: tier 2 distinct user logins in the month. resets every month
        - name: unique_visitors_network_subscribers_mtd
          description: tier 3 distinct user logins in the month. resets every month       
        
  - name: vw_rpt_network_ppv_actuals_estimates_forecast
    description: '{{ doc("vw_rpt_network_ppv_actuals_estimates_forecast") }}'
    columns:
        - name: event_date
          description: PPV event date
        - name: event_dttm
          description: PPV event date and time
        - name: event_name
          description: PPV event name
        - name: event_type
          description: Evenet type
        - name: event_reporting_type
          description: Event reporting type
        - name: adds_days_to_event
          description: adds day to event
        - name: adds_day_of_week
          description: adds day of the week
        - name: adds_date
          description: adds date
        - name: adds_time_to_event
          description: adds time to event
        - name: adds_time
          description: adds time
        - name: paid_adds
          description: paid adds
        - name: trial_adds
          description: trial adds
        - name: total_adds
          description: total adds
        - name: current_event_reporting_type
          description: current event reporting type
        - name: current_event_name
          description: current event name
        - name: current_event_date
          description: current event date
        - name: current_event_dttm
          description: current event date time
        - name: current_adds_date
          description: current adds date
        - name: current_adds_days_to_event
          description: current adds days to event
        - name: current_adds_day_of_week
          description: current adds day of the week
        - name: current_adds_time
          description: current adds time
        - name: ghw_adds_tillnow
          description: go home eek adds till now
        - name: ghw_adds_estimate
          description: go week home adds estimate
        - name: currentday_adds_tillnow
          description: currentday adds till now
        - name: currentday_adds_estimate
          description: current day adds estimate
        - name: weekend_adds_tillnow
          description: weekend adds till now
        - name: weekend_adds_estimate
          description: weekends adds estimate
        - name: current_day_forecast
          description: current day forecast
        - name: weekend_forecast
          description: weekend forecast
        
        
        
        
        
        
	
	
	
	
	
	




















  