CREATE VIEW
    vw_rpt_nl_daily_minxmin_lite_log_ratings COMMENT = '## Implementation Detail
*   Date        : 08/17/2020
*   Version     : 1.0
*   ViewName    : vw_rpt_nl_daily_minxmin_lite_log_ratings
*   Schema     : fds_nl
*   Contributor : Rahul Chandran
*   Description : Minute By Minture Ratings joining with Lite Log Report View consist of ratings of segments along with its details referencing from Minute By Minute Ratings joining with Lite Log daily table

## Maintenance Log
* Date : 08/17/2020 ; Developer: Rahul Chandran ; Change: Initial Version as a part of Phase 4b Project.'
    (
        broadcast_date_id COMMENT 'Broadcast Date ID field',
        broadcast_date COMMENT 'The date on when the program is broadcasted',
        src_broadcast_network_name COMMENT 'Broadcast Network Channel Name',
        src_program_name COMMENT 'Name of the Program',
        src_playback_period_cd COMMENT  'A comma separated list of data streams.' ,
        src_demographic_group COMMENT 'A comma separated list of demographic groups (e.g. Females 18 to 49 and Males 18 - 24 input as F18-49,M18-24).',
        program_telecast_rpt_starttime COMMENT 'Program Telecast Report Start Time',
        program_telecast_rpt_endtime COMMENT 'Program Telecast Report End Time',
        min_of_pgm_value COMMENT 'Metrics for Minute of program value',
        most_current_audience_avg_pct COMMENT  'Metrics for most current audience average percentage value',
        most_current_us_audience_avg_proj_000 COMMENT  'Metrics for most current US audience average projection in thousands',
        most_current_nw_cvg_area_avg_pct COMMENT 'Metrics for most current network coverage areas average percentage',
        showdbid COMMENT 'Show DB ID to uniquely identify the lite log of the program telecasted at a time',
        title COMMENT  'Title of the Program like NXT, RAW, SmackDown, etc.',
        subtitle COMMENT 'Subtitle of the program',
        episodenumber COMMENT 'Episode Number',
        airdate COMMENT  'The date on when the program aired',
        inpoint COMMENT 'The starting time of the particular segment',
        outpoint COMMENT 'The end time of the particular segment',
        modified_inpoint COMMENT 'Modified starting time of the particular segment by round it off to closest minute',
        modified_outpoint COMMENT 'Modified end time of the particular segment by round it off to closest minute',
        segmenttype COMMENT 'Type of Segment',
        COMMENT COMMENT  'The comment about the segment',
        matchtype COMMENT 'Type of the Match',
        talentactions COMMENT 'Describing the actions of talents',
        move COMMENT 'Describing the move',
        finishtype COMMENT 'The type of finish',
        recorddate COMMENT 'The date on when the program recorded',
        fileid COMMENT  'The File ID field',
        duration COMMENT   'Duration of the Segment',
        additionaltalent COMMENT 'gives the details of additional talents',
        announcers COMMENT 'Announcers of the program',
        matchtitle COMMENT  'Title of the match',
        venuelocation COMMENT 'Venue Location of the Program',
        venuename COMMENT  'Venue Name of the Program',
        issegmentmarker COMMENT 'Segment Marker',
        logentrydbid COMMENT  'Log Entry DB ID Field',
        logentryguid COMMENT 'Log Entry Guide',
        loggername COMMENT 'Name of the Logger',
        logname COMMENT 'Log Name',
        masterclipid COMMENT  'Master Clip ID',
        modifieddatetime COMMENT  'Modified Date Time',
        networkassetid COMMENT 'Network Asset ID',
        sponsors COMMENT 'Sponsors of the Program',
        weapon COMMENT 'Weapons used',
        season COMMENT 'Season details',
        source_ffed_name COMMENT 'source_ffed_name'
    ) AS
SELECT
    rpt_nl_daily_minxmin_lite_log_ratings.broadcast_date_id,
    rpt_nl_daily_minxmin_lite_log_ratings.broadcast_date,
    rpt_nl_daily_minxmin_lite_log_ratings.src_broadcast_network_name,
    rpt_nl_daily_minxmin_lite_log_ratings.src_program_name,
    rpt_nl_daily_minxmin_lite_log_ratings.src_playback_period_cd,
    rpt_nl_daily_minxmin_lite_log_ratings.src_demographic_group,
    rpt_nl_daily_minxmin_lite_log_ratings.program_telecast_rpt_starttime,
    rpt_nl_daily_minxmin_lite_log_ratings.program_telecast_rpt_endtime,
    rpt_nl_daily_minxmin_lite_log_ratings.min_of_pgm_value,
    rpt_nl_daily_minxmin_lite_log_ratings.most_current_audience_avg_pct,
    rpt_nl_daily_minxmin_lite_log_ratings.most_current_us_audience_avg_proj_000,
    rpt_nl_daily_minxmin_lite_log_ratings.most_current_nw_cvg_area_avg_pct,
    rpt_nl_daily_minxmin_lite_log_ratings.showdbid,
    rpt_nl_daily_minxmin_lite_log_ratings.title,
    rpt_nl_daily_minxmin_lite_log_ratings.subtitle,
    rpt_nl_daily_minxmin_lite_log_ratings.episodenumber,
    rpt_nl_daily_minxmin_lite_log_ratings.airdate,
    rpt_nl_daily_minxmin_lite_log_ratings.inpoint,
    rpt_nl_daily_minxmin_lite_log_ratings.outpoint,
    rpt_nl_daily_minxmin_lite_log_ratings.modified_inpoint,
    rpt_nl_daily_minxmin_lite_log_ratings.modified_outpoint,
    rpt_nl_daily_minxmin_lite_log_ratings.segmenttype,
    rpt_nl_daily_minxmin_lite_log_ratings."comment",
    rpt_nl_daily_minxmin_lite_log_ratings.matchtype,
    rpt_nl_daily_minxmin_lite_log_ratings.talentactions,
    rpt_nl_daily_minxmin_lite_log_ratings."move",
    rpt_nl_daily_minxmin_lite_log_ratings.finishtype,
    rpt_nl_daily_minxmin_lite_log_ratings.recorddate,
    rpt_nl_daily_minxmin_lite_log_ratings.fileid,
    rpt_nl_daily_minxmin_lite_log_ratings.duration,
    rpt_nl_daily_minxmin_lite_log_ratings.additionaltalent,
    rpt_nl_daily_minxmin_lite_log_ratings.announcers,
    rpt_nl_daily_minxmin_lite_log_ratings.matchtitle,
    rpt_nl_daily_minxmin_lite_log_ratings.venuelocation,
    rpt_nl_daily_minxmin_lite_log_ratings.venuename,
    rpt_nl_daily_minxmin_lite_log_ratings.issegmentmarker,
    rpt_nl_daily_minxmin_lite_log_ratings.logentrydbid,
    rpt_nl_daily_minxmin_lite_log_ratings.logentryguid,
    rpt_nl_daily_minxmin_lite_log_ratings.loggername,
    rpt_nl_daily_minxmin_lite_log_ratings.logname,
    rpt_nl_daily_minxmin_lite_log_ratings.masterclipid,
    rpt_nl_daily_minxmin_lite_log_ratings.modifieddatetime,
    rpt_nl_daily_minxmin_lite_log_ratings.networkassetid,
    rpt_nl_daily_minxmin_lite_log_ratings.sponsors,
    rpt_nl_daily_minxmin_lite_log_ratings.weapon,
    rpt_nl_daily_minxmin_lite_log_ratings.season,
    rpt_nl_daily_minxmin_lite_log_ratings.source_ffed_name
FROM
    rpt_nl_daily_minxmin_lite_log_ratings;

