CREATE TABLE RPT_KNTR_SCHEDULE_VH_DATA (
	DIM_DATE_ID NUMBER(38,0) COMMENT 'The broadcast date ID field',
	BROADCAST_DATE VARCHAR(30) COMMENT 'The date on when the WWE program broadcasted',
	SRC_WEEKDAY VARCHAR(20) COMMENT 'The day on when the WWE program broadcasted',
	MONTH_NAME VARCHAR(11) COMMENT 'The month name on when the WWE program broadcasted',
	MONTH_NUM NUMBER(38,0) COMMENT 'The month number on when the WWE program broadcasted',
	MODIFIED_MONTH VARCHAR(32) COMMENT 'Derived from broadcast_date; day part of broadcast_date replaced with '01'',
	YEAR NUMBER(38,0) COMMENT 'The broadcast year when the WWE program broadcasted',
	REGION VARCHAR(256) COMMENT 'The region of country from where the WWE program is telecasted',
	SRC_COUNTRY VARCHAR(50) COMMENT 'The country from where the WWE program is telecasted',
	BROADCAST_NETWORK_PREM_TYPE VARCHAR(30) COMMENT 'Indicates whether the channel is Pay / Free To Air',
	SRC_CHANNEL VARCHAR(70) COMMENT 'The channel name in which WWE program telecasted',
	DEMOGRAPHIC_TYPE VARCHAR(40) COMMENT 'The type of demographic group watched the WWE program',
	DEMOGRAPHIC_GROUP_NAME VARCHAR(40) COMMENT 'The demographic group name who watched the WWE program',
	SRC_SERIES VARCHAR(150) COMMENT 'Program name broadcasted on a partucular broadcast network (channel)',
	SERIES_EPISODE_NAME VARCHAR(256) COMMENT 'Name of the content broadcast',
	SERIES_EPISODE_NUM VARCHAR(30) COMMENT 'No.of episodes broadcast',
	SERIES_NAME VARCHAR(100) COMMENT 'Indicates WWE series name',
	SERIES_TYPE VARCHAR(30) COMMENT 'Indicates WWE series type',
	START_TIME VARCHAR(30) COMMENT 'Start Time of the WWE Program',
	END_TIME VARCHAR(30) COMMENT 'End Time of the WWE Program',
	DURATION_MINS NUMBER(38,0) COMMENT 'The duration of WWE Program in minutes',
	HD_FLAG VARCHAR(5) COMMENT 'Indicates whether the channel is HD or not',
	WEEK_START_DATE DATE COMMENT 'Calendar Year Week Start Date based on Broadcast Date',
	START_TIME_MODIFIED VARCHAR(57) COMMENT 'The Start Time of WWE Program rounded off to the closest hour in timestamp format',
	CHANNEL_1 VARCHAR(70) COMMENT 'The value will be 'Others', if the channel is broadcasting for more than an year and percentage of viewership of the channel (compared to total viewership of country) is <=0.01',
	PROGRAM_1 VARCHAR(100) COMMENT 'The value will be 'Others' for the programs other than 'RAW', 'SMACKDOWN', 'NXT', 'PPV', 'SUNDAY DHAMAAL', 'SATURDAY NIGHT', 'TOTAL BELLAS' and 'TOTAL DIVAS'',
	RAT_VALUE NUMBER(38,18) COMMENT 'The average rating value of the WWE program',
	VIEWING_HOURS NUMBER(38,4) COMMENT 'The viewing hours of WWE program by specified demographic group',
	AUD NUMBER(38,2) COMMENT 'The average audience who watched the WWE Program',
	REGIONAL_VIEWING_HOURS NUMBER(38,4) COMMENT 'The regional viewing hours of the demographic group on monthly-basis',
	ETL_BATCH_ID VARCHAR(26) COMMENT 'Unique ID of DBT Job used to insert the record',
	ETL_INSERT_USER_ID VARCHAR(15) COMMENT 'Unique ID of the DBT user that was used to insert the record',
	ETL_INSERT_REC_DTTM TIMESTAMP_TZ(9) COMMENT 'Date Time information on when the DBT inserted the record',
	ETL_UPDATE_USER_ID VARCHAR(1) COMMENT 'Unique ID of the DBT user which was used to update the record manually',
	ETL_UPDATE_REC_DTTM TIMESTAMP_NTZ(9) COMMENT 'Date Time information on when the record was updated'
)COMMENT='## Implementation Detail\n*   Date        : 07/24/2020\n*   Version     : 1.0\n*   TableName   : rpt_kntr_schedule_vh_data\n*   Schema     : fds_kntr\n*   Contributor : Rahul Chandran\n*   Description : WWE Program Schedule Viewing Hours Report table consist of rating and other details of WWE program schedule referencing from WWE Telecast Data table on daily-basis\n\n## Maintenance Log\n* Date : 07/24/2020 ; Developer: Rahul Chandran ; Change: Initial Version as a part of Phase 4b Project.'
;